//! True differential test: die-rust vs upstream DIE-engine golden baseline.
//!
//! Phase 15.1d: Compares die-rust scan output against pre-recorded golden
//! JSON baselines from upstream DIE-engine diec 4.0.0. The golden file is
//! generated by `tools/record_golden_baselines.py` and stored at
//! `tests/golden/upstream-die-baseline.json`.
//!
//! This test addresses the Phase 14 methodology flaw #1:
//! "Self-validating differential tests used hardcoded expectations instead
//! of comparing against actual upstream DIE-engine output."
//!
//! The comparison normalizes for known acceptable differences:
//! - Version string differences (rule version vs 3.21)
//! - "Unknown" detections on minimal samples (both produce these)
//! - Filetype naming (PE32 vs PE, ELF64 vs ELF, etc.)

#![forbid(unsafe_code)]

use die_core::cancel::CancellationToken;
use die_engine::{DatabaseBuilder, ScanFlags, scan_bytes};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Golden baseline JSON structure (matches record_golden_baselines.py output).
#[derive(Debug, Deserialize)]
struct GoldenBaseline {
    #[allow(dead_code)]
    diec_version: String,
    cases: std::collections::BTreeMap<String, GoldenCase>,
}

#[derive(Debug, Deserialize)]
struct GoldenCase {
    #[allow(dead_code)]
    exit_code: i32,
    json: GoldenJson,
    #[allow(dead_code)]
    last_error: String,
}

#[derive(Debug, Deserialize)]
struct GoldenJson {
    detects: Vec<GoldenDetect>,
}

#[derive(Debug, Deserialize)]
struct GoldenDetect {
    #[serde(default)]
    filetype: String,
    #[serde(default)]
    values: Vec<GoldenValue>,
}

#[derive(Debug, Deserialize, Serialize)]
struct GoldenValue {
    #[serde(default)]
    #[allow(dead_code)]
    name: String,
    #[serde(default)]
    #[allow(dead_code)]
    string: String,
    #[serde(default)]
    r#type: String,
    #[serde(default)]
    version: String,
}

/// Resolve the workspace root.
fn workspace_root() -> PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("."))
}

/// Resolve the golden baseline file.
fn golden_path() -> PathBuf {
    workspace_root()
        .join("tests")
        .join("golden")
        .join("upstream-die-baseline.json")
}

/// Resolve the upstream database directory.
fn db_root() -> String {
    workspace_root()
        .join("upstream")
        .join("Detect-It-Easy")
        .join("db")
        .to_str()
        .expect("utf-8 path")
        .to_string()
}

/// Normalize a detection type for comparison.
/// Upstream uses "format", "library", "compiler", etc.
/// die-rust uses the same type names.
fn normalize_type(s: &str) -> String {
    s.trim().to_lowercase()
}

/// Normalize a detection name for comparison.
/// Remove version suffixes and extra whitespace.
/// Apply known name aliases between upstream and die-rust.
fn normalize_name(s: &str) -> String {
    let lower = s.trim().to_lowercase();
    // Known name aliases: upstream vs die-rust naming differences.
    match lower.as_str() {
        "python bytecode compiled (.pyc)" | "python bytecode" => "python bytecode".to_string(),
        _ => lower,
    }
}

/// Normalize a version string for comparison.
fn normalize_version(s: &str) -> String {
    s.trim().to_string()
}

/// Extract (type, name, version) tuples from upstream golden format.
/// Upstream diec 4.0.0 reports filetype (e.g., "ZIP", "PE32", "ELF64") as
/// a separate field, and detection values in the "values" array.
///
/// die-rust produces detections for archive formats (Zip, tar, etc.) and
/// specific format detections (PDF, PNG, etc.) but does NOT produce
/// "format:PE" or "format:ELF" detections (these are handled by the probe
/// layer, not the rule engine). So we only map filetype to detections for
/// formats where die-rust also produces a rule-based detection.
fn golden_detections(case: &GoldenCase) -> Vec<(String, String, String)> {
    let mut result = Vec::new();
    for detect in &case.json.detects {
        // Map upstream filetype to (type, name) pairs that die-rust produces.
        // Only include mappings where die-rust also produces a corresponding
        // rule-based detection (not just probe-level format identification).
        let ft = detect.filetype.as_str();
        let ft_mapping = match ft {
            // ZIP/APK/JAR/IPA/RAR/TAR: upstream dispatch is exclusive —
            // these filetypes run only their own rule group, which emits
            // "Unknown" on minimal fixtures. die-rust now matches, so no
            // synthetic archive:* expectation is added.
            "PDF" => Some(("format", "PDF")),
            "CFBF" => Some(("format", "CFBF")),
            "DEX" => Some(("format", "DEX")),
            "JavaClass" | "Java Class" => Some(("format", "Java Class")),
            "PNG" => Some(("format", "PNG")),
            "JPEG" => Some(("format", "JPEG")),
            "Amiga Hunk" => Some(("format", "Amiga loadable file")),
            // NE/LE/LX: upstream promotes MZ subtypes via the e_lfanew
            // signature and emits only "Unknown" for these fixtures, which
            // die-rust now matches exactly. No synthetic mapping needed.
            // PE/ELF/Mach-O: die-rust does not produce format detections
            // for these (probe layer handles identification). Skip.
            // NPM: die-rust lacks NPM rule support (needs archive extraction).
            // This is a known gap tracked in Phase 15.6.
            _ => None,
        };

        // Check if there's already a real detection value for this filetype.
        // If so, don't add the filetype mapping (avoid duplicates).
        let has_real_value = detect.values.iter().any(|v| {
            let name = normalize_name(&v.name);
            name != "unknown" && !name.is_empty()
        });

        if let Some((t, n)) = ft_mapping
            && !has_real_value
        {
            result.push((normalize_type(t), normalize_name(n), String::new()));
        }

        // Add actual detection values (non-Unknown).
        for value in &detect.values {
            let name = normalize_name(&value.name);
            if name == "unknown" || name.is_empty() {
                continue;
            }
            result.push((
                normalize_type(&value.r#type),
                name,
                normalize_version(&value.version),
            ));
        }
    }
    result.sort();
    result
}

/// Extract (type, name, version) tuples from die-rust scan result.
/// Filters out "Unknown" detections to match upstream behavior on minimal
/// samples (upstream also produces "Unknown" but with different semantics).
fn rust_detections(result: &die_engine::ScanResult) -> Vec<(String, String, String)> {
    let mut result_vec = Vec::new();
    for d in &result.detections {
        // Skip "Unknown" detections — upstream produces these as filetype
        // placeholders, not real detections. die-rust may produce different
        // placeholder names.
        let name_lower = d.name.to_lowercase();
        if name_lower == "unknown" || name_lower == "empty file" {
            continue;
        }
        result_vec.push((
            normalize_type(&d.type_name),
            normalize_name(&d.name),
            normalize_version(""), // die-rust separates version into d.version
        ));
    }
    result_vec.sort();
    result_vec
}

/// Check if a golden detection is a "real" detection (not just "Unknown").
fn is_real_detection(_t: &str, n: &str) -> bool {
    !n.is_empty() && n != "unknown" && n != "empty file"
}

#[test]
fn true_differential_vs_upstream_golden() {
    let golden_file = golden_path();
    if !golden_file.exists() {
        eprintln!("SKIP: golden baseline not found at {golden_file:?}");
        eprintln!("Run: python3 tools/record_golden_baselines.py");
        return;
    }

    let golden_text = match std::fs::read_to_string(&golden_file) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("SKIP: cannot read golden file: {e}");
            return;
        }
    };

    let golden: GoldenBaseline = match serde_json::from_str(&golden_text) {
        Ok(g) => g,
        Err(e) => {
            eprintln!("SKIP: cannot parse golden JSON: {e}");
            return;
        }
    };

    let db_path = db_root();
    let database = match DatabaseBuilder::new(&db_path).build() {
        Ok(db) => db,
        Err(e) => {
            eprintln!("SKIP: upstream database not found: {e}");
            return;
        }
    };

    let corpus_dir = workspace_root().join("corpus");
    let cancel = CancellationToken::new();
    let mut tested = 0usize;
    let mut mismatches = Vec::new();

    // Known gaps: files where die-rust has known limitations that prevent
    // matching upstream output. These are tracked for Phase 15.6 closure.
    let known_gaps: &[&str] = &[
        // NPM rules require archive extraction + inner file scanning,
        // which die-rust does not yet support.
        "minimal-npm.tgz",
    ];

    for (filename, case) in &golden.cases {
        if known_gaps.contains(&filename.as_str()) {
            eprintln!("SKIP (known gap): {filename}");
            continue;
        }

        let filepath = corpus_dir.join(filename);
        if !filepath.exists() {
            eprintln!("SKIP: corpus file missing: {filename}");
            continue;
        }

        let data = match std::fs::read(&filepath) {
            Ok(d) => d,
            Err(e) => {
                mismatches.push(format!("{filename}: cannot read: {e}"));
                continue;
            }
        };

        let result = match scan_bytes(&database, filename, data, ScanFlags::default(), &cancel) {
            Ok(r) => r,
            Err(e) => {
                mismatches.push(format!("{filename}: scan error: {e}"));
                continue;
            }
        };

        // Phase 15.2c: Hard assertion — zero script exceptions.
        if !result.structured_diagnostics.is_empty() {
            let diags: Vec<String> = result
                .structured_diagnostics
                .iter()
                .map(|d| format!("{}: {}", d.file, d.message))
                .collect();
            mismatches.push(format!(
                "{filename}: {} script exception(s):\n  {}",
                result.structured_diagnostics.len(),
                diags.join("\n  ")
            ));
        }

        // Compare detections (only "real" detections, not "Unknown").
        let golden_detects: Vec<_> = golden_detections(case)
            .into_iter()
            .filter(|(t, n, _)| is_real_detection(t, n))
            .collect();

        let rust_detects: Vec<_> = rust_detections(&result);

        // Compare name sets (type+name pairs, ignoring version for now).
        let golden_names: std::collections::HashSet<(String, String)> = golden_detects
            .iter()
            .map(|(t, n, _)| (t.clone(), n.clone()))
            .collect();
        let rust_names: std::collections::HashSet<(String, String)> = rust_detects
            .iter()
            .map(|(t, n, _)| (t.clone(), n.clone()))
            .collect();

        if golden_names != rust_names {
            let missing: Vec<_> = golden_names.difference(&rust_names).collect();
            let extra: Vec<_> = rust_names.difference(&golden_names).collect();
            let mut msg = format!("{filename}: detection mismatch\n");
            if !missing.is_empty() {
                msg += &format!("  Missing (in golden but not rust): {:?}\n", missing);
            }
            if !extra.is_empty() {
                msg += &format!("  Extra (in rust but not golden): {:?}\n", extra);
            }
            mismatches.push(msg);
        }

        tested += 1;
    }

    assert!(tested > 0, "no golden cases were tested");
    assert!(
        mismatches.is_empty(),
        "true differential mismatches ({}):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
    eprintln!("true differential: {tested} cases tested, 0 mismatches vs upstream diec 4.0.0");
}
