//! `diec-nfd` — NFD/SpecAbstract second scan engine (Phase 21).
//!
//! Table-driven port of upstream `SpecAbstract` (MIT, horsicq) at
//! `upstream/DIE-engine/dep/SpecAbstract` @ `5188e047`. Signature tables
//! are generated by `tools/nfd_codegen.py`; scan passes mirror
//! `NFD_Binary::{signature,string,const,resources,memory,exp}Scan`.
//!
//! Currently ported dispatch: BINARY header/archive scans, MSDOS,
//! PE32/PE64 (header, entry-point chain, import hashes, resources,
//! section names, Rich records, deep section scans). Heuristic
//! `handle_*` version-enrichment is not yet ported — records carry
//! their static table metadata.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod elf;
mod engine;
pub mod parse;
mod pe;
mod records;
mod scans;
mod signature;
mod vi;

/// Generated name/type/filetype display tables and id constants.
pub mod gen_names;
/// Generated signature tables.
pub mod gen_tables;

pub use engine::{
    Detection, ScanOptions, ft_name, name_id, rtype_id, scan, sniff_ft, sniff_ft_named,
    supported_ft,
};
pub use scans::ScanRecord;
