//! Auto-generated by tools/nfd_codegen.py from
//! upstream/DIE-engine/dep/SpecAbstract @ 5188e047 (MIT, horsicq).
//! Do not edit; regenerate with `python3 tools/nfd_codegen.py`.

#![allow(missing_docs)]

/// Display strings for RECORD_NAME (index = u16 id).
pub static RECORD_NAME_STR: &[&str] = &[
    "12311134",
    "1337 Exe Crypter",
    "32Lite",
    "624",
    "7-Zip",
    "Aase",
    "ABC Cryptor",
    "ACProtect",
    "ActiveMARK",
    "Actual Installer",
    "Advanced Installer",
    "Advanced UPX Scrammbler",
    "AESObfuscator",
    "AffilliateEXE",
    "Again Nativity Crypter",
    "Agile .NET",
    "AHPacker",
    "AHTeam EP Protector",
    "AINEXE",
    "AIX",
    "Alchemy Mindworks",
    "Alex Protector",
    "ALIASOBJ",
    "Alibaba clang",
    "Alibaba Protection",
    "Alienyze",
    "Alipay clang",
    "Alipay Obfuscator",
    "Allatori Obfuscator",
    "Alloy",
    "Alpine clang",
    "Alpine Linux",
    "Aluwain",
    "Amiga",
    "ANDpakk2",
    "Android",
    "Android apksigner",
    "Android ARSC",
    "Android clang",
    "Android Gradle",
    "Android Jetpack",
    "Android Maven Plugin",
    "Android NDK",
    "Android SDK",
    "Android SignApk",
    "Android XML",
    "Anskya Polymorphic Packer",
    "AnslymPacker",
    "AntiDote",
    "Anti-LAME",
    "AntiLVL",
    "Apache Ant",
    "aPACK",
    "ApkEditor",
    "ApkEncryptor",
    "ApkModifier SignApk",
    "APKProtect",
    "ApkProtector",
    "APKS",
    "APK Signature Scheme",
    "ApkSigner",
    "ApkToolPlus",
    "apk-signer",
    "AppGuard",
    "AppImage",
    "Apple JDK",
    "Apple LLVM",
    "Apportable clang",
    "AppSolid",
    "ar",
    "AR Crypt",
    "ARJ",
    "Armadillo",
    "ARM Assembler",
    "ARM C",
    "ARM C/C++",
    "ARM Linker",
    "ARM NEON C/C++",
    "ARM Protector",
    "ARM/Thumb C/C++",
    "ARM/Thumb Macro Assembler",
    "Arnor BCPL",
    "AROS",
    "Artek Ada",
    "Arxan",
    "ASDPack",
    "ASM Guard",
    "ASPack",
    "ASPLinux",
    "ASProtect",
    "Ass Crypter",
    "Assembler",
    "AssemblyInvoke",
    "AU",
    "AutoIt",
    "Avast Antivirus",
    "AverCryptor",
    "AVI",
    "AVPACK",
    "AXE",
    "AZProtect",
    "Aztec C80",
    "Aztec C86",
    "Babel .NET",
    "Backdoor PE Compress Protector",
    "Baidu Protection",
    "Baidu Signature platform",
    "bambam",
    "Bangcle Protection",
    "BASIC",
    "Basic4Android",
    "BAT2EXEC",
    "BDS C",
    "BEA WebLogic",
    "BeRoEXEPacker",
    "Best Protection Kit",
    "Biohazard Crypter",
    "Bitmap Info Header",
    "BitRock Installer",
    "BitShape PE Crypt",
    "Blade Joiner",
    "Borland C/C++",
    "Borland C++",
    "Borland C++ Builder",
    "Borland Debug Info",
    "Borland Delphi",
    "Borland Delphi .NET",
    "Borland Object Pascal(Delphi)",
    "Borland OS Services",
    "BoxedApp Packer",
    "Break Into Pattern",
    "bridgeOS",
    "bridgeOS SDK",
    "Btworks CodeGuard",
    "BundleTool",
    "Burneye",
    "ByteDance-SecCompiler",
    "ByteGuard",
    "bzip2",
    "C",
    "CAB",
    "Carbon",
    "CauseWay",
    "CB80",
    "CBASIC",
    "CC by UniHackers",
    "CC by Vorontsov",
    "C/C++",
    "Celesty File Binder",
    "CExe",
    "Chromium Crashpad",
    "Cigicigi Crypter",
    "cil",
    "clang",
    "ClickTeam",
    "CliSecure",
    "Clive Partridge BCPL",
    "Cocoa",
    "CodeGear C++",
    "CodeGear C++ Builder",
    "CodeGear Delphi",
    "Codegear Object Pascal(Delphi)",
    "codesign",
    "CodeVeil",
    "CodeView Debug Info",
    "CodeWall",
    "COFF",
    "COMEX SignApk",
    "Comic Book Archive",
    "COMPACK",
    "Compound File Binary Format",
    "Confuser",
    "ConfuserEx",
    "CopyMinder",
    "CP/M",
    "C++",
    "CreateInstall",
    "Crinkler",
    "Crunch",
    "CryEXE",
    "CRYPACK",
    "Cryptable Seduction",
    "Crypt(Alex)",
    "CryptCom",
    "Crypt(Dismember)",
    "Crypter",
    "CryptExe",
    "Cryptic",
    "CrypToCrack Pe Protector",
    "Crypto Obfuscator For .Net",
    "Cryptor by Dismember",
    "Cryptor by Evil Genius",
    "CRyptOZ",
    "Crypt R.roads",
    "CSCRYPT Pro",
    "C#",
    "CVTOMF",
    "Cvtpgd",
    "CVTRES",
    "CWSDPMI",
    "Cygwin",
    "D",
    "d2j-apk-sign",
    "DalKrypt",
    "Dalvik",
    "DaRKSToP",
    "DBPE",
    "DCrypt Private",
    "DEB",
    "Debian clang",
    "Debian Linux",
    "DeepSea",
    "dePack",
    "DeployMaster",
    "DeSmet C",
    "DEX",
    "dex2jar",
    "DexGuard",
    "dexlib",
    "dexlib2",
    "DexMerge",
    "DexProtector",
    "DIET",
    "Digital Research",
    "Digital Research C",
    "Digital Research Pascal/MT+86",
    "Digital Research PL/I-80",
    "Digital Research PL/I-86",
    "DIGPAK",
    "Dingbaozeng native obfuscator",
    "DirTy Cryptor",
    "DjVu",
    "DMD",
    "DMD32",
    "DNGuard",
    "DOS/16M",
    "DOS/4G",
    ".BJFnt",
    "DotFix Nice Protect",
    "Dotfuscator",
    ".NET",
    ".NET Reactor",
    ".netshrink",
    ".NET Spider",
    ".NETZ",
    "dotools sign apk",
    "Draco",
    "DragonArmor",
    "Dropbox",
    "DVCLAL",
    "DWARF Debug Info",
    "dx",
    "DxShield",
    "DYAMAR",
    "DynASM",
    "EasyProtector",
    "Eazfuscator",
    "Eclipse",
    "ECMAScript",
    "ElecKey",
    "Embarcadero C++",
    "Embarcadero C++ Builder",
    "Embarcadero Delphi",
    "Embarcadero Delphi .NET",
    "Embarcadero Object Pascal(Delphi)",
    "Empty File",
    "EncryptPE",
    "ENIGMA",
    "Enigma Virtual Box",
    "EPACK",
    "!EP(EXE Pack)",
    "!EProt",
    "EPW",
    "Excelsior JET",
    "EXE2COM",
    "exe32pack",
    "EXE-COM Converters",
    "EXECrypt",
    "EXECryptor",
    "Executrix Compressor",
    "ExeFog",
    "EXEGUARD",
    "ExeJoiner",
    "ExeLITE",
    "EXELOCK",
    "EXELOCK 666",
    "Exemplar Installer",
    "EXEPACK",
    "EXE Password Protector",
    "ExeSax",
    "Exe Shield",
    "ExeStealth",
    "Export",
    "eXPressor",
    "eXPressor[Kernel32]",
    "eXPressor[User32]",
    "EZIP",
    "Fake signature",
    "Fakus Cryptor",
    "FASM",
    "Fast File Crypt",
    "fast-proxy",
    "fEaRz Crypter",
    "fEaRz Packer",
    "FenixOS",
    "FileShield",
    "FISH .NET",
    "Fish PE Packer",
    "FishPE Shield",
    "Flash Video",
    "Flex License Manager",
    "FlexNet Licensing",
    "Fortran",
    "Foundation",
    "Free Pascal",
    "FreeBSD",
    "FreeCryptor",
    "FSG",
    "FTL Modula-2",
    "GCC",
    "Generic",
    "Generic Linker",
    "Gentee Installer",
    "Gentoo Linux",
    "GhaZza CryPter",
    "Ghost Installer",
    "GIF",
    "G!X Protector",
    "GKripto",
    "GkSetup SFX",
    "GNU Assembler",
    "GNU ld",
    "Go",
    "Go32 Stub",
    "GoAsm",
    "Goat's PE Mutilator",
    "gold",
    "Goliath .NET",
    "GoLink",
    "Google",
    "Google Play",
    "GPatch",
    "GP-Install",
    "Guardian Stealth",
    "GZIP",
    "H4ck-y0u.org Crypter",
    "HAC Crew Crypter",
    "HackStop",
    "HaLV Crypter",
    "Hancom Linux",
    "Hdus-Wjus",
    "www.HiAPK.com",
    "Hide&Protect",
    "HidePE",
    "HikariObfuscator",
    "HiSoft Pascal",
    "HI-TECH C",
    "Hmimys Packer",
    "Hmimys's Protector",
    "Hochstrasser Modula-2",
    "HOODLUM",
    "Hound Hack Crypter",
    "HP-UX",
    "HTML",
    "HXS",
    "HyperTech Crackproof",
    "IBM JDK",
    "IBM PC BASIC Compiler",
    "IBM PC Fortran",
    "IBM PC Pascal",
    "ICE",
    "ICrypt",
    "IExpress",
    "iJiami",
    "iJiami LLVM",
    "IKVM.NET",
    "IL2CPP",
    "ILAsm",
    "Import",
    "INF Cryptor",
    "Inno Setup",
    "Inquartos Obfuscator",
    "install4j",
    "InstallAnywhere",
    "InstallAware",
    "InstallForge",
    "InstallShield",
    "Install Simple",
    "Intel iC-86",
    "InterSystems Pascal-Z",
    "iOS",
    "iOS SDK",
    "iOS App Store Package",
    "iPadOS",
    "iPB Protect",
    "iPhoneOS",
    "IRIX",
    "ISO 9660",
    "Jack",
    "JAM",
    "Janus Ada",
    "JAR",
    "Java",
    "Java compiled class",
    "JDK",
    "JDPack",
    "JetBrains",
    "jiagu",
    "JMCE",
    "JPEG",
    "JScript",
    "JVM",
    "KaOs PE-DLL eXecutable Undetecter",
    "KByS",
    "K!Cryptor",
    "KGB Crypter",
    "KiAms Cryptor",
    "Kiro",
    "Kiwi Version Obfuscator",
    "kkrunchy",
    "Kotlin",
    "Kratos Crypter",
    "Krypton",
    "Kur0k.X2.to",
    "LameCrypt",
    "lARP64",
    "Lattice C",
    "Lahey Fortran 90",
    "Lazarus",
    "lcclnk",
    "lcc-win",
    "ldc",
    "LGLZ",
    "LHA",
    "LHA's SFX",
    "LIAPP",
    "Lightning Crypter Private",
    "Lightning Crypter ScanTime",
    "Linux",
    "LLD",
    "LockTite+",
    "Logitech Modula-2",
    "LSCRYPT",
    "Lua compiled",
    "LuCypher",
    "LZEXE",
    "LZFSE",
    "Mac Catalyst",
    "Mac DriverKit",
    "Mac Firmware",
    "Mach-O FAT",
    "macOS",
    "macOS SDK",
    "Macrobject",
    "Mac OS",
    "Mac OS X",
    "Mal Packer",
    "Mandrake Linux",
    "Mark Williams C",
    "MASK",
    "MaskPE",
    "MASM",
    "MASM32",
    "MaxtoCode",
    "mClinux",
    "Medusah",
    "MEW10",
    "MEW11 SE",
    "MFC",
    "MI-C",
    "DDS MICRO-C",
    "Microsoft Access",
    "Microsoft BASIC Compiler",
    "Microsoft C",
    "Microsoft COBOL",
    "Microsoft Compiled HTML Help",
    "Microsoft Compound",
    "Microsoft C++",
    "Microsoft .NET Framework",
    "Microsoft Excel",
    "Microsoft Fortran",
    "Microsoft Installer(MSI)",
    "Microsoft linker",
    "Microsoft Linker Database",
    "Microsoft Office",
    "Microsoft Office Word",
    "Microsoft Pascal",
    "Microsoft Phoenix",
    "Microsoft QuickBASIC",
    "Microsoft QuickC",
    "Microsoft Visio",
    "Microsoft Visual Studio",
    "Microsoft WinHelp",
    "MIDPAK",
    "MinGW",
    "Minix",
    "Minke",
    "Mix C",
    "MKFPack",
    "Mobile Tencent Protect",
    "Modesto",
    "ModGuard",
    "mold",
    "MoleBox",
    "MoleBox Ultra",
    "Money Crypter",
    "Morphnah",
    "Mortal Team Crypter",
    "Mortal Team Crypter 2",
    "MoruK creW Crypter Private",
    "MOTODEV Studio for Android",
    "MP3",
    "MP4",
    "mPack",
    "MPRESS",
    "Mr Undectetable",
    "MS-DOS",
    "MSLRH",
    "Msys",
    "MSYS2",
    "MZ0oPE",
    "Nagain LLVM",
    "Nagapt Protection",
    "NakedPacker",
    "NASM",
    "NativeCryptor by DosX",
    "N-Code",
    "NeoLite",
    "NetBSD",
    "NetEase ApkSigner",
    "Nevada Fortran",
    "Nidhogg",
    "Nim",
    "N-Joiner",
    "N-Joy",
    "NME",
    "NoobyProtect",
    "NoodleCrypt",
    "North Star PE Shrinker",
    "NOS Installer",
    "NOSTUBLINKER",
    "noX Crypt",
    "nPack",
    "NQ Shield",
    "Nullsoft Scriptable Install System",
    "NSK",
    "NsPack",
    "Oberon-M",
    "Obfuscar",
    "Obfuscator-LLVM",
    "Obfuscator.NET 2009",
    "Objective-C",
    "Object Pascal",
    "Object Pascal(Delphi)",
    "Obsidium",
    "ollvm-tll(LLVM 6.0+Ollvm+Armariris)",
    "OneSpan Protection",
    "OpenBSD",
    "Open Document",
    "OpenJDK",
    "Open Source Code Crypter",
    "Open VMS",
    "Open VOS",
    "Open Watcom C/C++",
    "Opera",
    "Optlink",
    "Oracle Solaris Link Editors",
    "Oreans CodeVirtualizer",
    "ORiEN",
    "OS/2",
    "OSC-Crypter",
    "OS X",
    "Oxford Pascal",
    "p0ke Scrambler",
    "PACK",
    "Packman",
    "PACKWIN",
    "Pandora",
    "PangXie",
    "PC Guard",
    "PCOM",
    "PCShrink",
    "PDB",
    "PDB file link",
    "PDF",
    "PE-Armor",
    "PEBundle",
    "PECompact",
    "PECRYPT32",
    "PE Diminisher",
    "PE Encrypt",
    "PELock",
    "PELOCKnt",
    "PEnguinCrypt",
    "PE-PACK",
    "pepack's Protect",
    "PE Quake",
    "Perl",
    "PE-SHiELD",
    "PESpin",
    "Petite",
    "Petite.kernel32",
    "Petite.user32",
    "PeX",
    "PFE CX",
    "PGMPAK",
    "Phar Lap",
    "Phoenix Protector",
    "PHP",
    "PI Cryptor",
    "PKLITE",
    "PKLITE32",
    "PKSFX",
    "PKTINY",
    "PKZIP mini-sfx",
    "Plain",
    "Plex clang",
    "PLMX",
    "PMODE/W",
    "PNG",
    "Poke Crypter",
    "PolyCrypt PE",
    "POSIX",
    "PowerBASIC",
    "Mix Power C",
    "Private EXE Protector",
    "ProGuard",
    "PRO-PACK",
    "Pro Pascal",
    "PROTECT! EXE",
    "PseudoApkSigner",
    "Pub Crypter",
    "PUNiSHER",
    "PureBasic",
    "PussyCrypter",
    "PyInstaller",
    "Python",
    "QC Compiler",
    "qdbh",
    "Qihoo 360 Protection",
    "QML",
    "QNX",
    "QrYPt0r",
    "Qt",
    "Qt Installer",
    "QuickPack NT",
    "Microsoft QuickPascal",
    "R8",
    "Radialix",
    "RAR",
    "RCryptor(Russian Cryptor)",
    "RDG Tejon Crypter",
    "REC",
    "Red Hat Linux",
    "Relpack",
    "ReNET-pack",
    "Resource",
    "Resource Cursor",
    "Resource Dialog",
    "Resource Icon",
    "Resource Menu",
    "Resource String Table",
    "Resource Version Info",
    "REVProt",
    "RJcrush",
    "RLP",
    "RLPack",
    "RoguePack",
    "RosAsm",
    "Rich Text Format",
    "RTLink",
    "RTPatch",
    "Ruby",
    "Rust",
    "Safengine LLVM",
    "Safengine Shielden",
    "SandHook",
    "S-BASIC",
    "SC Obfuscator",
    "SC Pack",
    "SCRNCH",
    "SDProtector Pro",
    "SecNeo",
    "SecShell",
    "Secure Shade",
    "SecuROM",
    "sepOS",
    "SerGreen Appacker",
    "Setup Factory",
    "Setup-Specialist",
    "Sexe Crypter",
    "Shell",
    "Shrinker",
    "signatory",
    "signupdate",
    "SimbiOZ",
    "Sim Crypter",
    "Simple Crypter",
    "Simple Pack",
    "SingleJar",
    "Sixxpack",
    "Skater",
    "small-c",
    "Smart Assembly",
    "Smart Install Maker",
    "SmokeScreen Crypter",
    "Snapdragon LLVM ARM",
    "SnapProtect",
    "Snoop Crypt",
    "Soft Defender",
    "SoftSentry",
    "Software Compress",
    "Software Toolworks C/80",
    "SoftwareZator",
    "Solaris",
    "Sourcery CodeBench",
    "Sourcery CodeBench Lite",
    "Spices.Net",
    "$pirit",
    "Spoon Installer",
    "Spoon Studio",
    "Spoon Studio 2011",
    "Squeez Self Extractor",
    "Squirrel Installer",
    "STABS Debug Info",
    "StarForce",
    "StartOS Linux",
    "StasFodidoCryptor",
    "Stone's PE Encryptor",
    "Stony Brook Pascal+",
    "SunOS",
    "Sun WorkShop",
    "Sun WorkShop Compilers",
    "SuperSoft Ada",
    "SuperSoft C",
    "SuperSoft Fortran",
    "SUSE Linux",
    "SVK Protector",
    "SWF",
    "Swift",
    "Syllable",
    "Symbol Table",
    "tar",
    "Tarma Installer",
    "TCL Pascal",
    "tElock",
    "Tencent Legu",
    "Tencent Protection",
    "TGR Crypter",
    "The Best Cryptor [by FsK]",
    "Themida/Winlicense",
    "The Zone Crypter",
    "Thinstall(VMware ThinApp)",
    "Thumb C",
    "TIFF",
    "Tiny C",
    "TinyProg",
    "tiny-sign",
    "TopSpeed",
    "Total Commander Installer",
    "TTP Pack",
    "Tru64",
    "TsT Crypter",
    "True Type Font",
    "TTprotect",
    "Turbo Basic",
    "Turbo C",
    "Turbo C++",
    "Turbo linker",
    "Turbo Linux",
    "Turbo Pascal",
    "Turbo Studio",
    "Turkish Cyber Signature",
    "Turkojan Crypter",
    "tvOS",
    "tvOS SDK",
    "Ubuntu clang",
    "Ubuntu Linux",
    "UCEXE",
    "UnderGround Crypter",
    "UnDo Crypter",
    "Unicode",
    "Unicom SDK",
    "UniLink",
    "Unity",
    "Universal Tuple Compiler",
    "Unix",
    "Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "_Unknown",
    "unkOwn Crypter",
    "(Unknown)UPX-like",
    "Unopix",
    "UPX",
    "UTF-8",
    "Valve",
    "Van Valzah Pascal",
    "VB .NET",
    "Vbs To Exe",
    "VCasm-Protector",
    "Visual Component Library",
    "VCL PackageInfo",
    "VDog",
    "VeraCrypt",
    "Vine Linux",
    "Virbox Protector",
    "VirtualizeProtect",
    "Virtual Pascal",
    "Vise",
    "Visual Basic",
    "Visual C/C++",
    "Visual C#",
    "Visual Objects",
    "VMProtect",
    "VMUnpacker",
    "VMware",
    "VPacker",
    "Walle",
    "wangzehua LLVM",
    "watchOS",
    "watchOS SDK",
    "Watcom C",
    "Watcom C/C++",
    "Watcom Debug Info",
    "Watcom linker",
    "WAV",
    "WDOSX",
    "WebP",
    "Whitell Crypt",
    "Whitesmiths C",
    "WinACE",
    "Windows Authenticode",
    "WindOfCrypt",
    "Windows",
    "Windows Bitmap",
    "Windows CE",
    "Windows Cursor",
    "Windows Icon",
    "Windows Installer",
    "Windows Media",
    "Wind River Linux",
    "WingsCrypt",
    "WinKript",
    "WinRAR",
    "(Win)Upack",
    "WinZip",
    "Wise",
    "WiX Toolset",
    "WL-Crypt",
    "WL-Group Crypter",
    "WOLVERiNE Patcher",
    "WouThrs EXE Crypter",
    "WWPack",
    "WWPack32",
    "wxWidgets",
    "x86 Assembler",
    "xar",
    "XBOX",
    "Xcode",
    "Xcode ld",
    "XComp",
    "Xenocode",
    "Xenocode Postbuild",
    "Xenocode Postbuild 2009 for .NET",
    "Xenocode Postbuild 2010 for .NET",
    "Xenocode Virtual Application Studio 2009",
    "Xenocode Virtual Application Studio 2010",
    "Xenocode Virtual Application Studio 2010 ISV Edition",
    "Xenocode Virtual Application Studio 2012 ISV Edition",
    "Xenocode Virtual Application Studio 2013 ISV Edition",
    "XML",
    "XPack",
    "Xtreamlok",
    "Xtreme-Protector",
    "XVolkolak",
    "XZ",
    "Yandex",
    "Yano",
    "yidun",
    "Yoda's Crypter",
    "Yoda's Protector",
    "YZPack",
    "Z80 BCPL",
    "ZeldaCrypt",
    "Zig",
    "ZIP",
    "zlib",
    "Zortech C",
    "ZProtect",
    "RECORD_NAME_LZIP",
    "RECORD_NAME_LZMA",
    "RECORD_NAME_SKATERNET",
];

/// Display strings for RECORD_TYPE (index = u8 id).
pub static RECORD_TYPE_STR: &[&str] = &[
    "APK obfuscator",
    "APK Tool",
    "Archive",
    "Author",
    "Certificate",
    "Compiler",
    "Compressor",
    "Converter",
    "Corrupted data",
    "Creator",
    "Crypter",
    "Cryptor",
    "Data",
    "Database",
    "Debug data",
    "Document",
    "Dongle protection",
    "DOS extender",
    "Format",
    "Generic",
    "Image",
    "Installer",
    "Installer data",
    "JAR obfuscator",
    "Joiner",
    "Language",
    "Library",
    "Licensing",
    "Linker",
    "Loader",
    "Malware",
    ".NET compressor",
    ".NET obfuscator",
    "Obfuscator",
    "Operation system",
    "Overlay",
    "Package",
    "Packer",
    "Personal data",
    "PE Tool",
    "Platform",
    "Player",
    "Producer",
    "Protection",
    "Protector",
    "Protector data",
    "ROM",
    "SFX",
    "SFX data",
    "Sign tool",
    "Source code",
    "Stub",
    "Tool",
    "Trojan",
    "Unknown",
    "Virtual machine",
    "Virus",
];

/// Enum ordinal for XBinary::FT used by tables (index = u8 id).
pub static FT_STR: &[&str] = &[
    "FT_7Z",
    "FT_ACE",
    "FT_ACESFX",
    "FT_AGIS",
    "FT_AIN",
    "FT_AIX_BFF",
    "FT_AIX_BIGAF",
    "FT_ALDUS",
    "FT_ALZ",
    "FT_AMIGAHUNK",
    "FT_AMIGA_ADF",
    "FT_AMIGA_LZX",
    "FT_AMPK",
    "FT_ANDROIDASRC",
    "FT_ANDROIDXML",
    "FT_ANDROID_BOOT",
    "FT_AODOS",
    "FT_AP4",
    "FT_APK",
    "FT_APKS",
    "FT_APPLESINGLE",
    "FT_APPLE_2IMG",
    "FT_APRICOT",
    "FT_AR",
    "FT_ARC",
    "FT_ARCFS",
    "FT_ARCHIVE",
    "FT_ARCSFX",
    "FT_ARCV",
    "FT_ARCV2",
    "FT_ARCV2SFX",
    "FT_ARCV4",
    "FT_ARDI1_SFX",
    "FT_ARDI2_SFX",
    "FT_ARJ",
    "FT_ARJSFX",
    "FT_ARNI_SFX",
    "FT_ARQ",
    "FT_ARQSFX",
    "FT_ARTIPACK",
    "FT_ARX",
    "FT_AR_PDP11",
    "FT_ASAR",
    "FT_ASCEND",
    "FT_ASCEND_BACKUP",
    "FT_ASH0",
    "FT_ASYMETRIX",
    "FT_ASYMETRIXSFX",
    "FT_ATARIST",
    "FT_AUDIO",
    "FT_AVI",
    "FT_BCM",
    "FT_BEOS_PACKAGE",
    "FT_BIGF",
    "FT_BINARY",
    "FT_BINARY16",
    "FT_BINARY2",
    "FT_BINARY32",
    "FT_BINARY64",
    "FT_BINHEX",
    "FT_BINSH_SFX",
    "FT_BLUEBYTE_LIB",
    "FT_BMP",
    "FT_BOHEMIA_PBO",
    "FT_BOO",
    "FT_BORLAND_PACK",
    "FT_BROTLI",
    "FT_BSN",
    "FT_BSNSFX",
    "FT_BTH_PAK",
    "FT_BTOA",
    "FT_BUILD_GRP",
    "FT_BVRP_PAC",
    "FT_BWCF",
    "FT_BWDOS16M",
    "FT_BWF",
    "FT_BZIP1",
    "FT_BZIP2",
    "FT_BZIP2SFX",
    "FT_C64WRAPTOR",
    "FT_C64_T64",
    "FT_CAB",
    "FT_CABSFX",
    "FT_CFBF",
    "FT_CFBF_MSI",
    "FT_CFBF_WIX",
    "FT_CFL",
    "FT_CHIEFLZ",
    "FT_CHIEFLZMULTI",
    "FT_CHM",
    "FT_CHZ",
    "FT_CISO",
    "FT_CKP",
    "FT_CLAY",
    "FT_CLI_ASSEMBLY",
    "FT_CLOOP",
    "FT_CLP",
    "FT_CMP_ARCHIVE",
    "FT_COM",
    "FT_COMPACT_PRO",
    "FT_COMPAQ_LZH",
    "FT_COMPRESS",
    "FT_COPYQM",
    "FT_COREL_LTEC",
    "FT_CPIO",
    "FT_CPM_CRUNCH",
    "FT_CPM_LBR",
    "FT_CPM_LZH",
    "FT_CREATEINSTALL_SFX",
    "FT_CRU",
    "FT_CUR",
    "FT_DATA",
    "FT_DEARK_LEGACY_ARCHIVE",
    "FT_DEB",
    "FT_DER",
    "FT_DESCENT_HOG",
    "FT_DESCENT_HOG2",
    "FT_DEX",
    "FT_DISKJUGGLER_CDI",
    "FT_DISK_DOUBLER",
    "FT_DISK_DOUBLER_DDA2",
    "FT_DISK_DOUBLER_DDAR",
    "FT_DJVU",
    "FT_DMA",
    "FT_DMA_PACK",
    "FT_DMG",
    "FT_DMS",
    "FT_DN_ARCHIVE",
    "FT_DOCUMENT",
    "FT_DOOM_WAD",
    "FT_DOS16M",
    "FT_DOS4G",
    "FT_DPK",
    "FT_DSKEXP",
    "FT_DSL2",
    "FT_DTC",
    "FT_DT_PACK",
    "FT_EA",
    "FT_EALIB",
    "FT_EA_BIG",
    "FT_EA_REFPACK",
    "FT_ECM",
    "FT_ECM_PACK",
    "FT_EDC_PACKED",
    "FT_EDP",
    "FT_ELF",
    "FT_ELF32",
    "FT_ELF32_CABSFX",
    "FT_ELF32_FREEARCSFX",
    "FT_ELF32_RARSFX",
    "FT_ELF32_SFX",
    "FT_ELF32_ZIPSFX",
    "FT_ELF32_ZPAQSFX",
    "FT_ELF64",
    "FT_ELF64_CABSFX",
    "FT_ELF64_FREEARCSFX",
    "FT_ELF64_RARSFX",
    "FT_ELF64_SFX",
    "FT_ELF64_ZIPSFX",
    "FT_ELF64_ZPAQSFX",
    "FT_EML",
    "FT_EMT_IMAGE",
    "FT_EPFS_ARCHIVE",
    "FT_EPSF_SFX",
    "FT_ESP",
    "FT_EXE_EBOOKCREATOR",
    "FT_EXE_SBOOKBUILDER",
    "FT_FDI",
    "FT_FINEREADER_PACK",
    "FT_FINSTALL_ARCHIVE",
    "FT_FIZ",
    "FT_FLD",
    "FT_FLS",
    "FT_FMC1",
    "FT_FPAK",
    "FT_FREEARC",
    "FT_FREEARCSFX",
    "FT_FREEZE",
    "FT_FRONTPAGE_THEME",
    "FT_FTCOMP",
    "FT_GAMOS",
    "FT_GAS_HUFF",
    "FT_GENIUS_LIBRARY",
    "FT_GENTEE",
    "FT_GETTEXT_MO",
    "FT_GIF",
    "FT_GIT_OBJECT",
    "FT_GKSETUP",
    "FT_GLU",
    "FT_GOB",
    "FT_GOB2",
    "FT_GODOT_PCK",
    "FT_GPFPACK",
    "FT_GPINSTALL_SFX",
    "FT_GST_PACK",
    "FT_GTU",
    "FT_GZIP",
    "FT_GZIPSFX",
    "FT_HA",
    "FT_HAP",
    "FT_HDCOPY",
    "FT_HE_TLKB",
    "FT_HFE",
    "FT_HLB",
    "FT_HUFF",
    "FT_HZL",
    "FT_IBM_SPACK",
    "FT_IBM_ZPAK",
    "FT_ICC",
    "FT_ICO",
    "FT_IGF1",
    "FT_IGF2",
    "FT_IMAGE",
    "FT_IMP",
    "FT_INFOGRAMES_PAK",
    "FT_INNOSETUP",
    "FT_INSA",
    "FT_INSTALIT_DATA",
    "FT_INSTALIT_SFX",
    "FT_INSTALL4J_SFX",
    "FT_INSTALLANYWHERE_SFX",
    "FT_INSTALLSHIELD3_ARCHIVE",
    "FT_INSTALLSHIELD3_SFX",
    "FT_INSTALLSHIELD_BOOT",
    "FT_INSTALLSHIELD_LAUNCHER",
    "FT_INTEDU_FT",
    "FT_IPA",
    "FT_IRIX_SA",
    "FT_IRWINPAC",
    "FT_IS11",
    "FT_IS14_SFX",
    "FT_IS7_INX",
    "FT_ISCAB",
    "FT_ISO9660",
    "FT_ISSETUPSTREAM",
    "FT_IS_SKIN",
    "FT_IS_STORED",
    "FT_IVT",
    "FT_IZPACK",
    "FT_JAM",
    "FT_JAR",
    "FT_JASC_ARCHIVE",
    "FT_JAVACLASS",
    "FT_JBF",
    "FT_JETBBS",
    "FT_JGPAK",
    "FT_JM93",
    "FT_JPEG",
    "FT_KA_ARCHIVE",
    "FT_KBOOM",
    "FT_KOLIBRI_KPACK",
    "FT_KRML",
    "FT_KWAJ",
    "FT_KWAJSFX",
    "FT_LARC_PFX",
    "FT_LBR_COBOL",
    "FT_LE",
    "FT_LEGACY_CAT",
    "FT_LEGACY_RES",
    "FT_LEGACY_RSC",
    "FT_LHA",
    "FT_LHASFX",
    "FT_LIBDSK_IMAGE",
    "FT_LIF_COMPRESSED",
    "FT_LIM",
    "FT_LIZARD",
    "FT_LOFI",
    "FT_LOGITECH_COMPRESS",
    "FT_LPAK",
    "FT_LPAQ8",
    "FT_LSZ",
    "FT_LX",
    "FT_LZ4",
    "FT_LZ5",
    "FT_LZDIET",
    "FT_LZHCXP",
    "FT_LZIP",
    "FT_LZMA",
    "FT_LZO",
    "FT_LZPIS2",
    "FT_LZV1",
    "FT_LZWD",
    "FT_MACBINARY",
    "FT_MACHO",
    "FT_MACHO32",
    "FT_MACHO64",
    "FT_MACHOFAT",
    "FT_MAKESELF",
    "FT_MARC",
    "FT_MATHCAD_PACK",
    "FT_MAXIS_MXS",
    "FT_MBOX",
    "FT_MDH",
    "FT_MEGATECH_VOL",
    "FT_MHTML",
    "FT_MI10",
    "FT_MINIDUMP",
    "FT_MIZ",
    "FT_MLB_ARCHIVE",
    "FT_MP3",
    "FT_MP4",
    "FT_MPQ",
    "FT_MSCOMPRESS_SZ",
    "FT_MSDOS",
    "FT_MSDOS_COPYQM",
    "FT_MTREE",
    "FT_MUS",
    "FT_MVA",
    "FT_MWAVE_Z",
    "FT_NE",
    "FT_NERO_NRG",
    "FT_NETWARE_PACK",
    "FT_NETWARE_PACK2",
    "FT_NEXTSTEP_DISKIMAGE",
    "FT_NID",
    "FT_NOTETAB",
    "FT_NPACK",
    "FT_NPM",
    "FT_NSCRIPTER_NS2",
    "FT_NSCRIPTER_NSA",
    "FT_NSCRIPTER_SAR",
    "FT_NSIS",
    "FT_NTFS",
    "FT_OBFUSCATED_ARCHIVE",
    "FT_OPC",
    "FT_ORACLE_SQUEEZE",
    "FT_PACKIT",
    "FT_PAKLEO",
    "FT_PAL",
    "FT_PALM_PDB",
    "FT_PANORAMA",
    "FT_PAPERPORT",
    "FT_PARSEC_ARCHIVE",
    "FT_PAX",
    "FT_PCINSTALL",
    "FT_PCINSTALL_SFX",
    "FT_PCM",
    "FT_PCOMM_OS2",
    "FT_PC_SECURE",
    "FT_PDB",
    "FT_PDF",
    "FT_PE",
    "FT_PE32",
    "FT_PE32_7ZSFX",
    "FT_PE32_ACTUALINSTALLER",
    "FT_PE32_ADVANCEDINSTALLER",
    "FT_PE32_ASPACK",
    "FT_PE32_AUTOIT",
    "FT_PE32_BOXEDAPP",
    "FT_PE32_CABSFX",
    "FT_PE32_CLICKTEAM",
    "FT_PE32_CREATEINSTALL",
    "FT_PE32_ENIGMAVB",
    "FT_PE32_FREEARCSFX",
    "FT_PE32_FSG",
    "FT_PE32_IEXPRESS",
    "FT_PE32_INNOSETUP",
    "FT_PE32_INSTALLFORGE",
    "FT_PE32_INSTALLSHIELD",
    "FT_PE32_INSTALLSIMPLE",
    "FT_PE32_JUGGLOR",
    "FT_PE32_MEW",
    "FT_PE32_NSIS",
    "FT_PE32_NSPACK",
    "FT_PE32_PETITE",
    "FT_PE32_PFTW",
    "FT_PE32_RARSFX",
    "FT_PE32_SETUPFACTORY",
    "FT_PE32_SFX",
    "FT_PE32_SMARTINSTALL",
    "FT_PE32_TARMA",
    "FT_PE32_UPX",
    "FT_PE32_WINRARSFX",
    "FT_PE32_WIXBURN",
    "FT_PE32_YODA",
    "FT_PE32_ZIPSFX",
    "FT_PE32_ZPAQSFX",
    "FT_PE64",
    "FT_PE64_7ZSFX",
    "FT_PE64_ACTUALINSTALLER",
    "FT_PE64_ADVANCEDINSTALLER",
    "FT_PE64_AUTOIT",
    "FT_PE64_BOXEDAPP",
    "FT_PE64_CABSFX",
    "FT_PE64_CLICKTEAM",
    "FT_PE64_CREATEINSTALL",
    "FT_PE64_ENIGMAVB",
    "FT_PE64_FREEARCSFX",
    "FT_PE64_IEXPRESS",
    "FT_PE64_INNOSETUP",
    "FT_PE64_INSTALLFORGE",
    "FT_PE64_INSTALLSHIELD",
    "FT_PE64_INSTALLSIMPLE",
    "FT_PE64_NSIS",
    "FT_PE64_PFTW",
    "FT_PE64_RARSFX",
    "FT_PE64_SETUPFACTORY",
    "FT_PE64_SFX",
    "FT_PE64_SMARTINSTALL",
    "FT_PE64_TARMA",
    "FT_PE64_UPX",
    "FT_PE64_WINRARSFX",
    "FT_PE64_WIXBURN",
    "FT_PE64_ZIPSFX",
    "FT_PE64_ZPAQSFX",
    "FT_PEA",
    "FT_PIMP_SFX",
    "FT_PKT",
    "FT_PLAINTEXT",
    "FT_PMA",
    "FT_PMM",
    "FT_PM_DISKCOPY",
    "FT_PNG",
    "FT_POVLAB_LZH",
    "FT_POWERARC",
    "FT_POWERBOARD_BBS",
    "FT_PP20",
    "FT_PRINTSHOP_DELUXE",
    "FT_PROCESS",
    "FT_PSN_COMPRESS",
    "FT_PYC",
    "FT_PYINSTALLER_PYZ",
    "FT_PYINSTALLER_SFX",
    "FT_QCOW2",
    "FT_QDA",
    "FT_QDECK_QIP",
    "FT_QIP1",
    "FT_QNX_BASE",
    "FT_QSETUP",
    "FT_QT_QM",
    "FT_QUAKE_PAK",
    "FT_QUALITAS",
    "FT_QUANTUM",
    "FT_RAR",
    "FT_RARSFX",
    "FT_RAW_LZW15V",
    "FT_RCF",
    "FT_RECOGNITA",
    "FT_REGION",
    "FT_RENPY_RPA",
    "FT_RESOURCE_FORK",
    "FT_RGSSAD",
    "FT_RIB",
    "FT_RID",
    "FT_RIFF",
    "FT_RIVERSOFT",
    "FT_RNC",
    "FT_ROMFS",
    "FT_ROMPAQ",
    "FT_RPGMV_RESOURCE",
    "FT_RPM",
    "FT_RSVK",
    "FT_RTA",
    "FT_RTASFX",
    "FT_RTPATCH",
    "FT_RTPATCHSFX",
    "FT_RVZ",
    "FT_RZIP",
    "FT_SABDU_IMAGE",
    "FT_SAF",
    "FT_SAR",
    "FT_SBX_SFX",
    "FT_SCF",
    "FT_SCI",
    "FT_SCL",
    "FT_SEA_DATA",
    "FT_SECOND_NATURE",
    "FT_SETTLERS_FT",
    "FT_SFPACK",
    "FT_SFXGZIP",
    "FT_SHAR",
    "FT_SHRINKWRAP_IMAGE",
    "FT_SIGNATURE",
    "FT_SILMARILS",
    "FT_SLS",
    "FT_SM8",
    "FT_SMSIPAK",
    "FT_SND",
    "FT_SOFTPAQ1_SFX",
    "FT_SOFTPAQ_2",
    "FT_SOFTRONICS",
    "FT_SOLARIS_BOOT",
    "FT_SOLARIS_PKG",
    "FT_SOLITAIRE_DELUXE",
    "FT_SOS",
    "FT_SPIS",
    "FT_SPISSFX",
    "FT_SQ",
    "FT_SQLITE",
    "FT_SQUASHFS",
    "FT_SQX",
    "FT_SQZ",
    "FT_SQZSFX",
    "FT_SSBOB",
    "FT_SSM_MODULE",
    "FT_STK",
    "FT_STORK",
    "FT_STUNTS_DSI",
    "FT_STYLUS",
    "FT_SW",
    "FT_SWAG",
    "FT_SWAG_PACKET",
    "FT_SYDEX_SFX",
    "FT_SZDD",
    "FT_SZDDSFX",
    "FT_TAR",
    "FT_TARNEXTSTEP",
    "FT_TARX1",
    "FT_TARX2",
    "FT_TAR_BZIP2",
    "FT_TAR_GZ",
    "FT_TAR_LZ4",
    "FT_TAR_LZIP",
    "FT_TAR_LZMA",
    "FT_TAR_LZOP",
    "FT_TAR_XZ",
    "FT_TAR_Z",
    "FT_TAR_ZSTD",
    "FT_TEACY",
    "FT_TELEDISK",
    "FT_TERSE",
    "FT_TEXT",
    "FT_TGCF",
    "FT_TGCFSFX",
    "FT_TI99ARC",
    "FT_TIFF",
    "FT_TIVOLI",
    "FT_TNEF",
    "FT_TOPSPEED",
    "FT_TPS",
    "FT_TPWM",
    "FT_TRC",
    "FT_TRCPAK",
    "FT_TRDOS",
    "FT_TTF",
    "FT_TWS",
    "FT_UDF",
    "FT_ULEAD",
    "FT_UNICODE",
    "FT_UNICODE_BE",
    "FT_UNICODE_LE",
    "FT_UNIX_COMPACT",
    "FT_UNIX_PACK",
    "FT_UNKNOWN",
    "FT_UPX",
    "FT_UTF8",
    "FT_UU",
    "FT_VDI",
    "FT_VHD",
    "FT_VHDX",
    "FT_VIDEO",
    "FT_VISE_SFX",
    "FT_VMARC",
    "FT_VMDK",
    "FT_VMSDATABASE",
    "FT_VMSPCSI",
    "FT_VMSSAVESET",
    "FT_WARC",
    "FT_WARPIN",
    "FT_WASM",
    "FT_WAV",
    "FT_WBFS",
    "FT_WEBP",
    "FT_WII_LZ77",
    "FT_WII_U8",
    "FT_WII_WAD",
    "FT_WIM",
    "FT_WINTERMUTE_DCP",
    "FT_WINTERSOFT",
    "FT_WISE_SFX",
    "FT_WOLF_VSWAP",
    "FT_WPK",
    "FT_X64",
    "FT_XAR",
    "FT_XEDITPACK",
    "FT_XM",
    "FT_XML",
    "FT_XPAK",
    "FT_XZ",
    "FT_YENC",
    "FT_ZAP",
    "FT_ZCMP",
    "FT_ZFSF",
    "FT_ZIE",
    "FT_ZIP",
    "FT_ZIPSFX",
    "FT_ZLIB",
    "FT_ZLWB",
    "FT_ZOO",
    "FT_ZOOM",
    "FT_ZPAK",
    "FT_ZPAK_SFX",
    "FT_ZPAQ",
    "FT_ZPAQSFX",
    "FT_ZSTD",
    "FT_ZTC",
    "FT_ZXZIP",
    "FT_ZZ",
    "FT_ZZZ",
];

/// Named constants for RECORD_NAME ids used by heuristic code.
pub mod name {
    pub const RECORD_NAME_12311134: u16 = 0;
    pub const RECORD_NAME_1337EXECRYPTER: u16 = 1;
    pub const RECORD_NAME_32LITE: u16 = 2;
    pub const RECORD_NAME_624: u16 = 3;
    pub const RECORD_NAME_7Z: u16 = 4;
    pub const RECORD_NAME_AASE: u16 = 5;
    pub const RECORD_NAME_ABCCRYPTOR: u16 = 6;
    pub const RECORD_NAME_ACPROTECT: u16 = 7;
    pub const RECORD_NAME_ACTIVEMARK: u16 = 8;
    pub const RECORD_NAME_ACTUALINSTALLER: u16 = 9;
    pub const RECORD_NAME_ADVANCEDINSTALLER: u16 = 10;
    pub const RECORD_NAME_ADVANCEDUPXSCRAMMBLER: u16 = 11;
    pub const RECORD_NAME_AESOBFUSCATOR: u16 = 12;
    pub const RECORD_NAME_AFFILLIATEEXE: u16 = 13;
    pub const RECORD_NAME_AGAINNATIVITYCRYPTER: u16 = 14;
    pub const RECORD_NAME_AGILENET: u16 = 15;
    pub const RECORD_NAME_AHPACKER: u16 = 16;
    pub const RECORD_NAME_AHTEAMEPPROTECTOR: u16 = 17;
    pub const RECORD_NAME_AINEXE: u16 = 18;
    pub const RECORD_NAME_AIX: u16 = 19;
    pub const RECORD_NAME_ALCHEMYMINDWORKS: u16 = 20;
    pub const RECORD_NAME_ALEXPROTECTOR: u16 = 21;
    pub const RECORD_NAME_ALIASOBJ: u16 = 22;
    pub const RECORD_NAME_ALIBABACLANG: u16 = 23;
    pub const RECORD_NAME_ALIBABAPROTECTION: u16 = 24;
    pub const RECORD_NAME_ALIENYZE: u16 = 25;
    pub const RECORD_NAME_ALIPAYCLANG: u16 = 26;
    pub const RECORD_NAME_ALIPAYOBFUSCATOR: u16 = 27;
    pub const RECORD_NAME_ALLATORIOBFUSCATOR: u16 = 28;
    pub const RECORD_NAME_ALLOY: u16 = 29;
    pub const RECORD_NAME_ALPINECLANG: u16 = 30;
    pub const RECORD_NAME_ALPINELINUX: u16 = 31;
    pub const RECORD_NAME_ALUWAIN: u16 = 32;
    pub const RECORD_NAME_AMIGA: u16 = 33;
    pub const RECORD_NAME_ANDPAKK2: u16 = 34;
    pub const RECORD_NAME_ANDROID: u16 = 35;
    pub const RECORD_NAME_ANDROIDAPKSIGNER: u16 = 36;
    pub const RECORD_NAME_ANDROIDARSC: u16 = 37;
    pub const RECORD_NAME_ANDROIDCLANG: u16 = 38;
    pub const RECORD_NAME_ANDROIDGRADLE: u16 = 39;
    pub const RECORD_NAME_ANDROIDJETPACK: u16 = 40;
    pub const RECORD_NAME_ANDROIDMAVENPLUGIN: u16 = 41;
    pub const RECORD_NAME_ANDROIDNDK: u16 = 42;
    pub const RECORD_NAME_ANDROIDSDK: u16 = 43;
    pub const RECORD_NAME_ANDROIDSIGNAPK: u16 = 44;
    pub const RECORD_NAME_ANDROIDXML: u16 = 45;
    pub const RECORD_NAME_ANSKYAPOLYMORPHICPACKER: u16 = 46;
    pub const RECORD_NAME_ANSLYMPACKER: u16 = 47;
    pub const RECORD_NAME_ANTIDOTE: u16 = 48;
    pub const RECORD_NAME_ANTILAME: u16 = 49;
    pub const RECORD_NAME_ANTILVL: u16 = 50;
    pub const RECORD_NAME_APACHEANT: u16 = 51;
    pub const RECORD_NAME_APACK: u16 = 52;
    pub const RECORD_NAME_APKEDITOR: u16 = 53;
    pub const RECORD_NAME_APKENCRYPTOR: u16 = 54;
    pub const RECORD_NAME_APKMODIFIERSIGNAPK: u16 = 55;
    pub const RECORD_NAME_APKPROTECT: u16 = 56;
    pub const RECORD_NAME_APKPROTECTOR: u16 = 57;
    pub const RECORD_NAME_APKS: u16 = 58;
    pub const RECORD_NAME_APKSIGNATURESCHEME: u16 = 59;
    pub const RECORD_NAME_APKSIGNER: u16 = 60;
    pub const RECORD_NAME_APKTOOLPLUS: u16 = 61;
    pub const RECORD_NAME_APK_SIGNER: u16 = 62;
    pub const RECORD_NAME_APPGUARD: u16 = 63;
    pub const RECORD_NAME_APPIMAGE: u16 = 64;
    pub const RECORD_NAME_APPLEJDK: u16 = 65;
    pub const RECORD_NAME_APPLELLVM: u16 = 66;
    pub const RECORD_NAME_APPORTABLECLANG: u16 = 67;
    pub const RECORD_NAME_APPSOLID: u16 = 68;
    pub const RECORD_NAME_AR: u16 = 69;
    pub const RECORD_NAME_ARCRYPT: u16 = 70;
    pub const RECORD_NAME_ARJ: u16 = 71;
    pub const RECORD_NAME_ARMADILLO: u16 = 72;
    pub const RECORD_NAME_ARMASSEMBLER: u16 = 73;
    pub const RECORD_NAME_ARMC: u16 = 74;
    pub const RECORD_NAME_ARMCCPP: u16 = 75;
    pub const RECORD_NAME_ARMLINKER: u16 = 76;
    pub const RECORD_NAME_ARMNEONCCPP: u16 = 77;
    pub const RECORD_NAME_ARMPROTECTOR: u16 = 78;
    pub const RECORD_NAME_ARMTHUMBCCPP: u16 = 79;
    pub const RECORD_NAME_ARMTHUMBMACROASSEMBLER: u16 = 80;
    pub const RECORD_NAME_ARNORBCPL: u16 = 81;
    pub const RECORD_NAME_AROS: u16 = 82;
    pub const RECORD_NAME_ARTEKADA: u16 = 83;
    pub const RECORD_NAME_ARXAN: u16 = 84;
    pub const RECORD_NAME_ASDPACK: u16 = 85;
    pub const RECORD_NAME_ASMGUARD: u16 = 86;
    pub const RECORD_NAME_ASPACK: u16 = 87;
    pub const RECORD_NAME_ASPLINUX: u16 = 88;
    pub const RECORD_NAME_ASPROTECT: u16 = 89;
    pub const RECORD_NAME_ASSCRYPTER: u16 = 90;
    pub const RECORD_NAME_ASSEMBLER: u16 = 91;
    pub const RECORD_NAME_ASSEMBLYINVOKE: u16 = 92;
    pub const RECORD_NAME_AU: u16 = 93;
    pub const RECORD_NAME_AUTOIT: u16 = 94;
    pub const RECORD_NAME_AVASTANTIVIRUS: u16 = 95;
    pub const RECORD_NAME_AVERCRYPTOR: u16 = 96;
    pub const RECORD_NAME_AVI: u16 = 97;
    pub const RECORD_NAME_AVPACK: u16 = 98;
    pub const RECORD_NAME_AXE: u16 = 99;
    pub const RECORD_NAME_AZPROTECT: u16 = 100;
    pub const RECORD_NAME_AZTECC80: u16 = 101;
    pub const RECORD_NAME_AZTECC86: u16 = 102;
    pub const RECORD_NAME_BABELNET: u16 = 103;
    pub const RECORD_NAME_BACKDOORPECOMPRESSPROTECTOR: u16 = 104;
    pub const RECORD_NAME_BAIDUPROTECTION: u16 = 105;
    pub const RECORD_NAME_BAIDUSIGNATUREPLATFORM: u16 = 106;
    pub const RECORD_NAME_BAMBAM: u16 = 107;
    pub const RECORD_NAME_BANGCLEPROTECTION: u16 = 108;
    pub const RECORD_NAME_BASIC: u16 = 109;
    pub const RECORD_NAME_BASIC4ANDROID: u16 = 110;
    pub const RECORD_NAME_BAT2EXEC: u16 = 111;
    pub const RECORD_NAME_BDSC: u16 = 112;
    pub const RECORD_NAME_BEAWEBLOGIC: u16 = 113;
    pub const RECORD_NAME_BEROEXEPACKER: u16 = 114;
    pub const RECORD_NAME_BESTPROTECTIONKIT: u16 = 115;
    pub const RECORD_NAME_BIOHAZARDCRYPTER: u16 = 116;
    pub const RECORD_NAME_BITMAPINFOHEADER: u16 = 117;
    pub const RECORD_NAME_BITROCKINSTALLER: u16 = 118;
    pub const RECORD_NAME_BITSHAPEPECRYPT: u16 = 119;
    pub const RECORD_NAME_BLADEJOINER: u16 = 120;
    pub const RECORD_NAME_BORLANDCCPP: u16 = 121;
    pub const RECORD_NAME_BORLANDCPP: u16 = 122;
    pub const RECORD_NAME_BORLANDCPPBUILDER: u16 = 123;
    pub const RECORD_NAME_BORLANDDEBUGINFO: u16 = 124;
    pub const RECORD_NAME_BORLANDDELPHI: u16 = 125;
    pub const RECORD_NAME_BORLANDDELPHIDOTNET: u16 = 126;
    pub const RECORD_NAME_BORLANDOBJECTPASCALDELPHI: u16 = 127;
    pub const RECORD_NAME_BORLANDOSSERVICES: u16 = 128;
    pub const RECORD_NAME_BOXEDAPPPACKER: u16 = 129;
    pub const RECORD_NAME_BREAKINTOPATTERN: u16 = 130;
    pub const RECORD_NAME_BRIDGEOS: u16 = 131;
    pub const RECORD_NAME_BRIDGEOSSDK: u16 = 132;
    pub const RECORD_NAME_BTWORKSCODEGUARD: u16 = 133;
    pub const RECORD_NAME_BUNDLETOOL: u16 = 134;
    pub const RECORD_NAME_BURNEYE: u16 = 135;
    pub const RECORD_NAME_BYTEDANCESECCOMPILER: u16 = 136;
    pub const RECORD_NAME_BYTEGUARD: u16 = 137;
    pub const RECORD_NAME_BZIP2: u16 = 138;
    pub const RECORD_NAME_C: u16 = 139;
    pub const RECORD_NAME_CAB: u16 = 140;
    pub const RECORD_NAME_CARBON: u16 = 141;
    pub const RECORD_NAME_CAUSEWAY: u16 = 142;
    pub const RECORD_NAME_CB80: u16 = 143;
    pub const RECORD_NAME_CBASIC: u16 = 144;
    pub const RECORD_NAME_CCBYUNIHACKERS: u16 = 145;
    pub const RECORD_NAME_CCBYVORONTSOV: u16 = 146;
    pub const RECORD_NAME_CCPP: u16 = 147;
    pub const RECORD_NAME_CELESTYFILEBINDER: u16 = 148;
    pub const RECORD_NAME_CEXE: u16 = 149;
    pub const RECORD_NAME_CHROMIUMCRASHPAD: u16 = 150;
    pub const RECORD_NAME_CIGICIGICRYPTER: u16 = 151;
    pub const RECORD_NAME_CIL: u16 = 152;
    pub const RECORD_NAME_CLANG: u16 = 153;
    pub const RECORD_NAME_CLICKTEAM: u16 = 154;
    pub const RECORD_NAME_CLISECURE: u16 = 155;
    pub const RECORD_NAME_CLIVEPARTRIDGEBCPL: u16 = 156;
    pub const RECORD_NAME_COCOA: u16 = 157;
    pub const RECORD_NAME_CODEGEARCPP: u16 = 158;
    pub const RECORD_NAME_CODEGEARCPPBUILDER: u16 = 159;
    pub const RECORD_NAME_CODEGEARDELPHI: u16 = 160;
    pub const RECORD_NAME_CODEGEAROBJECTPASCALDELPHI: u16 = 161;
    pub const RECORD_NAME_CODESIGN: u16 = 162;
    pub const RECORD_NAME_CODEVEIL: u16 = 163;
    pub const RECORD_NAME_CODEVIEWDEBUGINFO: u16 = 164;
    pub const RECORD_NAME_CODEWALL: u16 = 165;
    pub const RECORD_NAME_COFF: u16 = 166;
    pub const RECORD_NAME_COMEXSIGNAPK: u16 = 167;
    pub const RECORD_NAME_COMICBOOKARCHIVE: u16 = 168;
    pub const RECORD_NAME_COMPACK: u16 = 169;
    pub const RECORD_NAME_COMPOUNDFILEBINARYFORMAT: u16 = 170;
    pub const RECORD_NAME_CONFUSER: u16 = 171;
    pub const RECORD_NAME_CONFUSEREX: u16 = 172;
    pub const RECORD_NAME_COPYMINDER: u16 = 173;
    pub const RECORD_NAME_CPM: u16 = 174;
    pub const RECORD_NAME_CPP: u16 = 175;
    pub const RECORD_NAME_CREATEINSTALL: u16 = 176;
    pub const RECORD_NAME_CRINKLER: u16 = 177;
    pub const RECORD_NAME_CRUNCH: u16 = 178;
    pub const RECORD_NAME_CRYEXE: u16 = 179;
    pub const RECORD_NAME_CRYPACK: u16 = 180;
    pub const RECORD_NAME_CRYPTABLESEDUCATION: u16 = 181;
    pub const RECORD_NAME_CRYPTBYALEX: u16 = 182;
    pub const RECORD_NAME_CRYPTCOM: u16 = 183;
    pub const RECORD_NAME_CRYPTDISMEMBER: u16 = 184;
    pub const RECORD_NAME_CRYPTER: u16 = 185;
    pub const RECORD_NAME_CRYPTEXE: u16 = 186;
    pub const RECORD_NAME_CRYPTIC: u16 = 187;
    pub const RECORD_NAME_CRYPTOCRACKPEPROTECTOR: u16 = 188;
    pub const RECORD_NAME_CRYPTOOBFUSCATORFORNET: u16 = 189;
    pub const RECORD_NAME_CRYPTORBYDISMEMBER: u16 = 190;
    pub const RECORD_NAME_CRYPTORBYEVILGENIUS: u16 = 191;
    pub const RECORD_NAME_CRYPTOZ: u16 = 192;
    pub const RECORD_NAME_CRYPTRROADS: u16 = 193;
    pub const RECORD_NAME_CSCRYPTPRO: u16 = 194;
    pub const RECORD_NAME_CSHARP: u16 = 195;
    pub const RECORD_NAME_CVTOMF: u16 = 196;
    pub const RECORD_NAME_CVTPGD: u16 = 197;
    pub const RECORD_NAME_CVTRES: u16 = 198;
    pub const RECORD_NAME_CWSDPMI: u16 = 199;
    pub const RECORD_NAME_CYGWIN: u16 = 200;
    pub const RECORD_NAME_D: u16 = 201;
    pub const RECORD_NAME_D2JAPKSIGN: u16 = 202;
    pub const RECORD_NAME_DALKRYPT: u16 = 203;
    pub const RECORD_NAME_DALVIK: u16 = 204;
    pub const RECORD_NAME_DARKSTOP: u16 = 205;
    pub const RECORD_NAME_DBPE: u16 = 206;
    pub const RECORD_NAME_DCRYPTPRIVATE: u16 = 207;
    pub const RECORD_NAME_DEB: u16 = 208;
    pub const RECORD_NAME_DEBIANCLANG: u16 = 209;
    pub const RECORD_NAME_DEBIANLINUX: u16 = 210;
    pub const RECORD_NAME_DEEPSEA: u16 = 211;
    pub const RECORD_NAME_DEPACK: u16 = 212;
    pub const RECORD_NAME_DEPLOYMASTER: u16 = 213;
    pub const RECORD_NAME_DESMETC: u16 = 214;
    pub const RECORD_NAME_DEX: u16 = 215;
    pub const RECORD_NAME_DEX2JAR: u16 = 216;
    pub const RECORD_NAME_DEXGUARD: u16 = 217;
    pub const RECORD_NAME_DEXLIB: u16 = 218;
    pub const RECORD_NAME_DEXLIB2: u16 = 219;
    pub const RECORD_NAME_DEXMERGE: u16 = 220;
    pub const RECORD_NAME_DEXPROTECTOR: u16 = 221;
    pub const RECORD_NAME_DIET: u16 = 222;
    pub const RECORD_NAME_DIGITALRESEARCH: u16 = 223;
    pub const RECORD_NAME_DIGITALRESEARCHC: u16 = 224;
    pub const RECORD_NAME_DIGITALRESEARCHMTPASCAL: u16 = 225;
    pub const RECORD_NAME_DIGITALRESEARCHPLI80: u16 = 226;
    pub const RECORD_NAME_DIGITALRESEARCHPLI86: u16 = 227;
    pub const RECORD_NAME_DIGPAK: u16 = 228;
    pub const RECORD_NAME_DINGBAOZENGNATIVEOBFUSCATOR: u16 = 229;
    pub const RECORD_NAME_DIRTYCRYPTOR: u16 = 230;
    pub const RECORD_NAME_DJVU: u16 = 231;
    pub const RECORD_NAME_DMD: u16 = 232;
    pub const RECORD_NAME_DMD32: u16 = 233;
    pub const RECORD_NAME_DNGUARD: u16 = 234;
    pub const RECORD_NAME_DOS16M: u16 = 235;
    pub const RECORD_NAME_DOS4G: u16 = 236;
    pub const RECORD_NAME_DOTBJFNT: u16 = 237;
    pub const RECORD_NAME_DOTFIXNICEPROTECT: u16 = 238;
    pub const RECORD_NAME_DOTFUSCATOR: u16 = 239;
    pub const RECORD_NAME_DOTNET: u16 = 240;
    pub const RECORD_NAME_DOTNETREACTOR: u16 = 241;
    pub const RECORD_NAME_DOTNETSHRINK: u16 = 242;
    pub const RECORD_NAME_DOTNETSPIDER: u16 = 243;
    pub const RECORD_NAME_DOTNETZ: u16 = 244;
    pub const RECORD_NAME_DOTOOLSSIGNAPK: u16 = 245;
    pub const RECORD_NAME_DRACO: u16 = 246;
    pub const RECORD_NAME_DRAGONARMOR: u16 = 247;
    pub const RECORD_NAME_DROPBOX: u16 = 248;
    pub const RECORD_NAME_DVCLAL: u16 = 249;
    pub const RECORD_NAME_DWARFDEBUGINFO: u16 = 250;
    pub const RECORD_NAME_DX: u16 = 251;
    pub const RECORD_NAME_DXSHIELD: u16 = 252;
    pub const RECORD_NAME_DYAMAR: u16 = 253;
    pub const RECORD_NAME_DYNASM: u16 = 254;
    pub const RECORD_NAME_EASYPROTECTOR: u16 = 255;
    pub const RECORD_NAME_EAZFUSCATOR: u16 = 256;
    pub const RECORD_NAME_ECLIPSE: u16 = 257;
    pub const RECORD_NAME_ECMASCRIPT: u16 = 258;
    pub const RECORD_NAME_ELECKEY: u16 = 259;
    pub const RECORD_NAME_EMBARCADEROCPP: u16 = 260;
    pub const RECORD_NAME_EMBARCADEROCPPBUILDER: u16 = 261;
    pub const RECORD_NAME_EMBARCADERODELPHI: u16 = 262;
    pub const RECORD_NAME_EMBARCADERODELPHIDOTNET: u16 = 263;
    pub const RECORD_NAME_EMBARCADEROOBJECTPASCALDELPHI: u16 = 264;
    pub const RECORD_NAME_EMPTYFILE: u16 = 265;
    pub const RECORD_NAME_ENCRYPTPE: u16 = 266;
    pub const RECORD_NAME_ENIGMA: u16 = 267;
    pub const RECORD_NAME_ENIGMAVIRTUALBOX: u16 = 268;
    pub const RECORD_NAME_EPACK: u16 = 269;
    pub const RECORD_NAME_EPEXEPACK: u16 = 270;
    pub const RECORD_NAME_EPROT: u16 = 271;
    pub const RECORD_NAME_EPW: u16 = 272;
    pub const RECORD_NAME_EXCELSIORJET: u16 = 273;
    pub const RECORD_NAME_EXE2COM: u16 = 274;
    pub const RECORD_NAME_EXE32PACK: u16 = 275;
    pub const RECORD_NAME_EXECOMCONVERTERS: u16 = 276;
    pub const RECORD_NAME_EXECRYPT: u16 = 277;
    pub const RECORD_NAME_EXECRYPTOR: u16 = 278;
    pub const RECORD_NAME_EXECUTRIX: u16 = 279;
    pub const RECORD_NAME_EXEFOG: u16 = 280;
    pub const RECORD_NAME_EXEGUARD: u16 = 281;
    pub const RECORD_NAME_EXEJOINER: u16 = 282;
    pub const RECORD_NAME_EXELITE: u16 = 283;
    pub const RECORD_NAME_EXELOCK: u16 = 284;
    pub const RECORD_NAME_EXELOCK666: u16 = 285;
    pub const RECORD_NAME_EXEMPLARINSTALLER: u16 = 286;
    pub const RECORD_NAME_EXEPACK: u16 = 287;
    pub const RECORD_NAME_EXEPASSWORDPROTECTOR: u16 = 288;
    pub const RECORD_NAME_EXESAX: u16 = 289;
    pub const RECORD_NAME_EXESHIELD: u16 = 290;
    pub const RECORD_NAME_EXESTEALTH: u16 = 291;
    pub const RECORD_NAME_EXPORT: u16 = 292;
    pub const RECORD_NAME_EXPRESSOR: u16 = 293;
    pub const RECORD_NAME_EXPRESSOR_KERNEL32: u16 = 294;
    pub const RECORD_NAME_EXPRESSOR_USER32: u16 = 295;
    pub const RECORD_NAME_EZIP: u16 = 296;
    pub const RECORD_NAME_FAKESIGNATURE: u16 = 297;
    pub const RECORD_NAME_FAKUSCRYPTOR: u16 = 298;
    pub const RECORD_NAME_FASM: u16 = 299;
    pub const RECORD_NAME_FASTFILECRYPT: u16 = 300;
    pub const RECORD_NAME_FASTPROXY: u16 = 301;
    pub const RECORD_NAME_FEARZCRYPTER: u16 = 302;
    pub const RECORD_NAME_FEARZPACKER: u16 = 303;
    pub const RECORD_NAME_FENIXOS: u16 = 304;
    pub const RECORD_NAME_FILESHIELD: u16 = 305;
    pub const RECORD_NAME_FISHNET: u16 = 306;
    pub const RECORD_NAME_FISHPEPACKER: u16 = 307;
    pub const RECORD_NAME_FISHPESHIELD: u16 = 308;
    pub const RECORD_NAME_FLASHVIDEO: u16 = 309;
    pub const RECORD_NAME_FLEXLM: u16 = 310;
    pub const RECORD_NAME_FLEXNET: u16 = 311;
    pub const RECORD_NAME_FORTRAN: u16 = 312;
    pub const RECORD_NAME_FOUNDATION: u16 = 313;
    pub const RECORD_NAME_FPC: u16 = 314;
    pub const RECORD_NAME_FREEBSD: u16 = 315;
    pub const RECORD_NAME_FREECRYPTOR: u16 = 316;
    pub const RECORD_NAME_FSG: u16 = 317;
    pub const RECORD_NAME_FTLMODULA2: u16 = 318;
    pub const RECORD_NAME_GCC: u16 = 319;
    pub const RECORD_NAME_GENERIC: u16 = 320;
    pub const RECORD_NAME_GENERICLINKER: u16 = 321;
    pub const RECORD_NAME_GENTEEINSTALLER: u16 = 322;
    pub const RECORD_NAME_GENTOOLINUX: u16 = 323;
    pub const RECORD_NAME_GHAZZACRYPTER: u16 = 324;
    pub const RECORD_NAME_GHOSTINSTALLER: u16 = 325;
    pub const RECORD_NAME_GIF: u16 = 326;
    pub const RECORD_NAME_GIXPROTECTOR: u16 = 327;
    pub const RECORD_NAME_GKRIPTO: u16 = 328;
    pub const RECORD_NAME_GKSETUPSFX: u16 = 329;
    pub const RECORD_NAME_GNUASSEMBLER: u16 = 330;
    pub const RECORD_NAME_GNULINKER: u16 = 331;
    pub const RECORD_NAME_GO: u16 = 332;
    pub const RECORD_NAME_GO32STUB: u16 = 333;
    pub const RECORD_NAME_GOASM: u16 = 334;
    pub const RECORD_NAME_GOATSPEMUTILATOR: u16 = 335;
    pub const RECORD_NAME_GOLD: u16 = 336;
    pub const RECORD_NAME_GOLIATHNET: u16 = 337;
    pub const RECORD_NAME_GOLINK: u16 = 338;
    pub const RECORD_NAME_GOOGLE: u16 = 339;
    pub const RECORD_NAME_GOOGLEPLAY: u16 = 340;
    pub const RECORD_NAME_GPATCH: u16 = 341;
    pub const RECORD_NAME_GPINSTALL: u16 = 342;
    pub const RECORD_NAME_GUARDIANSTEALTH: u16 = 343;
    pub const RECORD_NAME_GZIP: u16 = 344;
    pub const RECORD_NAME_H4CKY0UORGCRYPTER: u16 = 345;
    pub const RECORD_NAME_HACCREWCRYPTER: u16 = 346;
    pub const RECORD_NAME_HACKSTOP: u16 = 347;
    pub const RECORD_NAME_HALVCRYPTER: u16 = 348;
    pub const RECORD_NAME_HANCOMLINUX: u16 = 349;
    pub const RECORD_NAME_HDUS_WJUS: u16 = 350;
    pub const RECORD_NAME_HIAPKCOM: u16 = 351;
    pub const RECORD_NAME_HIDEANDPROTECT: u16 = 352;
    pub const RECORD_NAME_HIDEPE: u16 = 353;
    pub const RECORD_NAME_HIKARIOBFUSCATOR: u16 = 354;
    pub const RECORD_NAME_HISOFTPASCAL: u16 = 355;
    pub const RECORD_NAME_HITECHC: u16 = 356;
    pub const RECORD_NAME_HMIMYSPACKER: u16 = 357;
    pub const RECORD_NAME_HMIMYSPROTECTOR: u16 = 358;
    pub const RECORD_NAME_HOCHSTRASSERMODULA2: u16 = 359;
    pub const RECORD_NAME_HOODLUM: u16 = 360;
    pub const RECORD_NAME_HOUNDHACKCRYPTER: u16 = 361;
    pub const RECORD_NAME_HPUX: u16 = 362;
    pub const RECORD_NAME_HTML: u16 = 363;
    pub const RECORD_NAME_HXS: u16 = 364;
    pub const RECORD_NAME_HYPERTECHCRACKPROOF: u16 = 365;
    pub const RECORD_NAME_IBMJDK: u16 = 366;
    pub const RECORD_NAME_IBMPCBASIC: u16 = 367;
    pub const RECORD_NAME_IBMPCFORTRAN: u16 = 368;
    pub const RECORD_NAME_IBMPCPASCAL: u16 = 369;
    pub const RECORD_NAME_ICE: u16 = 370;
    pub const RECORD_NAME_ICRYPT: u16 = 371;
    pub const RECORD_NAME_IEXPRESS: u16 = 372;
    pub const RECORD_NAME_IJIAMI: u16 = 373;
    pub const RECORD_NAME_IJIAMILLVM: u16 = 374;
    pub const RECORD_NAME_IKVMDOTNET: u16 = 375;
    pub const RECORD_NAME_IL2CPP: u16 = 376;
    pub const RECORD_NAME_ILASM: u16 = 377;
    pub const RECORD_NAME_IMPORT: u16 = 378;
    pub const RECORD_NAME_INFCRYPTOR: u16 = 379;
    pub const RECORD_NAME_INNOSETUP: u16 = 380;
    pub const RECORD_NAME_INQUARTOSOBFUSCATOR: u16 = 381;
    pub const RECORD_NAME_INSTALL4J: u16 = 382;
    pub const RECORD_NAME_INSTALLANYWHERE: u16 = 383;
    pub const RECORD_NAME_INSTALLAWARE: u16 = 384;
    pub const RECORD_NAME_INSTALLFORGE: u16 = 385;
    pub const RECORD_NAME_INSTALLSHIELD: u16 = 386;
    pub const RECORD_NAME_INSTALLSIMPLE: u16 = 387;
    pub const RECORD_NAME_INTELIC86: u16 = 388;
    pub const RECORD_NAME_INTERSYSTEMSPASCALZ: u16 = 389;
    pub const RECORD_NAME_IOS: u16 = 390;
    pub const RECORD_NAME_IOSSDK: u16 = 391;
    pub const RECORD_NAME_IPA: u16 = 392;
    pub const RECORD_NAME_IPADOS: u16 = 393;
    pub const RECORD_NAME_IPBPROTECT: u16 = 394;
    pub const RECORD_NAME_IPHONEOS: u16 = 395;
    pub const RECORD_NAME_IRIX: u16 = 396;
    pub const RECORD_NAME_ISO9660: u16 = 397;
    pub const RECORD_NAME_JACK: u16 = 398;
    pub const RECORD_NAME_JAM: u16 = 399;
    pub const RECORD_NAME_JANUSADA: u16 = 400;
    pub const RECORD_NAME_JAR: u16 = 401;
    pub const RECORD_NAME_JAVA: u16 = 402;
    pub const RECORD_NAME_JAVACOMPILEDCLASS: u16 = 403;
    pub const RECORD_NAME_JDK: u16 = 404;
    pub const RECORD_NAME_JDPACK: u16 = 405;
    pub const RECORD_NAME_JETBRAINS: u16 = 406;
    pub const RECORD_NAME_JIAGU: u16 = 407;
    pub const RECORD_NAME_JMCE: u16 = 408;
    pub const RECORD_NAME_JPEG: u16 = 409;
    pub const RECORD_NAME_JSCRIPT: u16 = 410;
    pub const RECORD_NAME_JVM: u16 = 411;
    pub const RECORD_NAME_KAOSPEDLLEXECUTABLEUNDETECTER: u16 = 412;
    pub const RECORD_NAME_KBYS: u16 = 413;
    pub const RECORD_NAME_KCRYPTOR: u16 = 414;
    pub const RECORD_NAME_KGBCRYPTER: u16 = 415;
    pub const RECORD_NAME_KIAMSCRYPTOR: u16 = 416;
    pub const RECORD_NAME_KIRO: u16 = 417;
    pub const RECORD_NAME_KIWIVERSIONOBFUSCATOR: u16 = 418;
    pub const RECORD_NAME_KKRUNCHY: u16 = 419;
    pub const RECORD_NAME_KOTLIN: u16 = 420;
    pub const RECORD_NAME_KRATOSCRYPTER: u16 = 421;
    pub const RECORD_NAME_KRYPTON: u16 = 422;
    pub const RECORD_NAME_KUR0KX2TO: u16 = 423;
    pub const RECORD_NAME_LAMECRYPT: u16 = 424;
    pub const RECORD_NAME_LARP64: u16 = 425;
    pub const RECORD_NAME_LATTICEC: u16 = 426;
    pub const RECORD_NAME_LAYHEYFORTRAN90: u16 = 427;
    pub const RECORD_NAME_LAZARUS: u16 = 428;
    pub const RECORD_NAME_LCCLNK: u16 = 429;
    pub const RECORD_NAME_LCCWIN: u16 = 430;
    pub const RECORD_NAME_LDC: u16 = 431;
    pub const RECORD_NAME_LGLZ: u16 = 432;
    pub const RECORD_NAME_LHA: u16 = 433;
    pub const RECORD_NAME_LHASSFX: u16 = 434;
    pub const RECORD_NAME_LIAPP: u16 = 435;
    pub const RECORD_NAME_LIGHTNINGCRYPTERPRIVATE: u16 = 436;
    pub const RECORD_NAME_LIGHTNINGCRYPTERSCANTIME: u16 = 437;
    pub const RECORD_NAME_LINUX: u16 = 438;
    pub const RECORD_NAME_LLD: u16 = 439;
    pub const RECORD_NAME_LOCKTITE: u16 = 440;
    pub const RECORD_NAME_LOGITECHMODULA2: u16 = 441;
    pub const RECORD_NAME_LSCRYPRT: u16 = 442;
    pub const RECORD_NAME_LUACOMPILED: u16 = 443;
    pub const RECORD_NAME_LUCYPHER: u16 = 444;
    pub const RECORD_NAME_LZEXE: u16 = 445;
    pub const RECORD_NAME_LZFSE: u16 = 446;
    pub const RECORD_NAME_MACCATALYST: u16 = 447;
    pub const RECORD_NAME_MACDRIVERKIT: u16 = 448;
    pub const RECORD_NAME_MACFIRMWARE: u16 = 449;
    pub const RECORD_NAME_MACHOFAT: u16 = 450;
    pub const RECORD_NAME_MACOS: u16 = 451;
    pub const RECORD_NAME_MACOSSDK: u16 = 452;
    pub const RECORD_NAME_MACROBJECT: u16 = 453;
    pub const RECORD_NAME_MAC_OS: u16 = 454;
    pub const RECORD_NAME_MAC_OS_X: u16 = 455;
    pub const RECORD_NAME_MALPACKER: u16 = 456;
    pub const RECORD_NAME_MANDRAKELINUX: u16 = 457;
    pub const RECORD_NAME_MARKWILLIAMSC: u16 = 458;
    pub const RECORD_NAME_MASK: u16 = 459;
    pub const RECORD_NAME_MASKPE: u16 = 460;
    pub const RECORD_NAME_MASM: u16 = 461;
    pub const RECORD_NAME_MASM32: u16 = 462;
    pub const RECORD_NAME_MAXTOCODE: u16 = 463;
    pub const RECORD_NAME_MCLINUX: u16 = 464;
    pub const RECORD_NAME_MEDUSAH: u16 = 465;
    pub const RECORD_NAME_MEW10: u16 = 466;
    pub const RECORD_NAME_MEW11SE: u16 = 467;
    pub const RECORD_NAME_MFC: u16 = 468;
    pub const RECORD_NAME_MIC: u16 = 469;
    pub const RECORD_NAME_MICROC: u16 = 470;
    pub const RECORD_NAME_MICROSOFTACCESS: u16 = 471;
    pub const RECORD_NAME_MICROSOFTBASIC: u16 = 472;
    pub const RECORD_NAME_MICROSOFTC: u16 = 473;
    pub const RECORD_NAME_MICROSOFTCOBOL: u16 = 474;
    pub const RECORD_NAME_MICROSOFTCOMPILEDHTMLHELP: u16 = 475;
    pub const RECORD_NAME_MICROSOFTCOMPOUND: u16 = 476;
    pub const RECORD_NAME_MICROSOFTCPP: u16 = 477;
    pub const RECORD_NAME_MICROSOFTDOTNETFRAMEWORK: u16 = 478;
    pub const RECORD_NAME_MICROSOFTEXCEL: u16 = 479;
    pub const RECORD_NAME_MICROSOFTFORTRAN: u16 = 480;
    pub const RECORD_NAME_MICROSOFTINSTALLER: u16 = 481;
    pub const RECORD_NAME_MICROSOFTLINKER: u16 = 482;
    pub const RECORD_NAME_MICROSOFTLINKERDATABASE: u16 = 483;
    pub const RECORD_NAME_MICROSOFTOFFICE: u16 = 484;
    pub const RECORD_NAME_MICROSOFTOFFICEWORD: u16 = 485;
    pub const RECORD_NAME_MICROSOFTPASCAL: u16 = 486;
    pub const RECORD_NAME_MICROSOFTPHOENIX: u16 = 487;
    pub const RECORD_NAME_MICROSOFTQUICKBASIC: u16 = 488;
    pub const RECORD_NAME_MICROSOFTQUICKC: u16 = 489;
    pub const RECORD_NAME_MICROSOFTVISIO: u16 = 490;
    pub const RECORD_NAME_MICROSOFTVISUALSTUDIO: u16 = 491;
    pub const RECORD_NAME_MICROSOFTWINHELP: u16 = 492;
    pub const RECORD_NAME_MIDPAK: u16 = 493;
    pub const RECORD_NAME_MINGW: u16 = 494;
    pub const RECORD_NAME_MINIX: u16 = 495;
    pub const RECORD_NAME_MINKE: u16 = 496;
    pub const RECORD_NAME_MIXC: u16 = 497;
    pub const RECORD_NAME_MKFPACK: u16 = 498;
    pub const RECORD_NAME_MOBILETENCENTPROTECT: u16 = 499;
    pub const RECORD_NAME_MODESTO: u16 = 500;
    pub const RECORD_NAME_MODGUARD: u16 = 501;
    pub const RECORD_NAME_MOLD: u16 = 502;
    pub const RECORD_NAME_MOLEBOX: u16 = 503;
    pub const RECORD_NAME_MOLEBOXULTRA: u16 = 504;
    pub const RECORD_NAME_MONEYCRYPTER: u16 = 505;
    pub const RECORD_NAME_MORPHNAH: u16 = 506;
    pub const RECORD_NAME_MORTALTEAMCRYPTER: u16 = 507;
    pub const RECORD_NAME_MORTALTEAMCRYPTER2: u16 = 508;
    pub const RECORD_NAME_MORUKCREWCRYPTERPRIVATE: u16 = 509;
    pub const RECORD_NAME_MOTODEVSTUDIOFORANDROID: u16 = 510;
    pub const RECORD_NAME_MP3: u16 = 511;
    pub const RECORD_NAME_MP4: u16 = 512;
    pub const RECORD_NAME_MPACK: u16 = 513;
    pub const RECORD_NAME_MPRESS: u16 = 514;
    pub const RECORD_NAME_MRUNDECTETABLE: u16 = 515;
    pub const RECORD_NAME_MSDOS: u16 = 516;
    pub const RECORD_NAME_MSLRH: u16 = 517;
    pub const RECORD_NAME_MSYS: u16 = 518;
    pub const RECORD_NAME_MSYS2: u16 = 519;
    pub const RECORD_NAME_MZ0OPE: u16 = 520;
    pub const RECORD_NAME_NAGAINLLVM: u16 = 521;
    pub const RECORD_NAME_NAGAPTPROTECTION: u16 = 522;
    pub const RECORD_NAME_NAKEDPACKER: u16 = 523;
    pub const RECORD_NAME_NASM: u16 = 524;
    pub const RECORD_NAME_NATIVECRYPTORBYDOSX: u16 = 525;
    pub const RECORD_NAME_NCODE: u16 = 526;
    pub const RECORD_NAME_NEOLITE: u16 = 527;
    pub const RECORD_NAME_NETBSD: u16 = 528;
    pub const RECORD_NAME_NETEASEAPKSIGNER: u16 = 529;
    pub const RECORD_NAME_NEVADAFORTRAN: u16 = 530;
    pub const RECORD_NAME_NIDHOGG: u16 = 531;
    pub const RECORD_NAME_NIM: u16 = 532;
    pub const RECORD_NAME_NJOINER: u16 = 533;
    pub const RECORD_NAME_NJOY: u16 = 534;
    pub const RECORD_NAME_NME: u16 = 535;
    pub const RECORD_NAME_NOOBYPROTECT: u16 = 536;
    pub const RECORD_NAME_NOODLECRYPT: u16 = 537;
    pub const RECORD_NAME_NORTHSTARPESHRINKER: u16 = 538;
    pub const RECORD_NAME_NOSINSTALLER: u16 = 539;
    pub const RECORD_NAME_NOSTUBLINKER: u16 = 540;
    pub const RECORD_NAME_NOXCRYPT: u16 = 541;
    pub const RECORD_NAME_NPACK: u16 = 542;
    pub const RECORD_NAME_NQSHIELD: u16 = 543;
    pub const RECORD_NAME_NSIS: u16 = 544;
    pub const RECORD_NAME_NSK: u16 = 545;
    pub const RECORD_NAME_NSPACK: u16 = 546;
    pub const RECORD_NAME_OBERONM: u16 = 547;
    pub const RECORD_NAME_OBFUSCAR: u16 = 548;
    pub const RECORD_NAME_OBFUSCATORLLVM: u16 = 549;
    pub const RECORD_NAME_OBFUSCATORNET2009: u16 = 550;
    pub const RECORD_NAME_OBJECTIVEC: u16 = 551;
    pub const RECORD_NAME_OBJECTPASCAL: u16 = 552;
    pub const RECORD_NAME_OBJECTPASCALDELPHI: u16 = 553;
    pub const RECORD_NAME_OBSIDIUM: u16 = 554;
    pub const RECORD_NAME_OLLVMTLL: u16 = 555;
    pub const RECORD_NAME_ONESPANPROTECTION: u16 = 556;
    pub const RECORD_NAME_OPENBSD: u16 = 557;
    pub const RECORD_NAME_OPENDOCUMENT: u16 = 558;
    pub const RECORD_NAME_OPENJDK: u16 = 559;
    pub const RECORD_NAME_OPENSOURCECODECRYPTER: u16 = 560;
    pub const RECORD_NAME_OPENVMS: u16 = 561;
    pub const RECORD_NAME_OPENVOS: u16 = 562;
    pub const RECORD_NAME_OPENWATCOMCCPP: u16 = 563;
    pub const RECORD_NAME_OPERA: u16 = 564;
    pub const RECORD_NAME_OPTLINK: u16 = 565;
    pub const RECORD_NAME_ORACLESOLARISLINKEDITORS: u16 = 566;
    pub const RECORD_NAME_OREANSCODEVIRTUALIZER: u16 = 567;
    pub const RECORD_NAME_ORIEN: u16 = 568;
    pub const RECORD_NAME_OS2: u16 = 569;
    pub const RECORD_NAME_OSCCRYPTER: u16 = 570;
    pub const RECORD_NAME_OS_X: u16 = 571;
    pub const RECORD_NAME_OXFORDPASCAL: u16 = 572;
    pub const RECORD_NAME_P0KESCRAMBLER: u16 = 573;
    pub const RECORD_NAME_PACK: u16 = 574;
    pub const RECORD_NAME_PACKMAN: u16 = 575;
    pub const RECORD_NAME_PACKWIN: u16 = 576;
    pub const RECORD_NAME_PANDORA: u16 = 577;
    pub const RECORD_NAME_PANGXIE: u16 = 578;
    pub const RECORD_NAME_PCGUARD: u16 = 579;
    pub const RECORD_NAME_PCOM: u16 = 580;
    pub const RECORD_NAME_PCSHRINK: u16 = 581;
    pub const RECORD_NAME_PDB: u16 = 582;
    pub const RECORD_NAME_PDBFILELINK: u16 = 583;
    pub const RECORD_NAME_PDF: u16 = 584;
    pub const RECORD_NAME_PEARMOR: u16 = 585;
    pub const RECORD_NAME_PEBUNDLE: u16 = 586;
    pub const RECORD_NAME_PECOMPACT: u16 = 587;
    pub const RECORD_NAME_PECRYPT32: u16 = 588;
    pub const RECORD_NAME_PEDIMINISHER: u16 = 589;
    pub const RECORD_NAME_PEENCRYPT: u16 = 590;
    pub const RECORD_NAME_PELOCK: u16 = 591;
    pub const RECORD_NAME_PELOCKNT: u16 = 592;
    pub const RECORD_NAME_PENGUINCRYPT: u16 = 593;
    pub const RECORD_NAME_PEPACK: u16 = 594;
    pub const RECORD_NAME_PEPACKSPROTECT: u16 = 595;
    pub const RECORD_NAME_PEQUAKE: u16 = 596;
    pub const RECORD_NAME_PERL: u16 = 597;
    pub const RECORD_NAME_PESHIELD: u16 = 598;
    pub const RECORD_NAME_PESPIN: u16 = 599;
    pub const RECORD_NAME_PETITE: u16 = 600;
    pub const RECORD_NAME_PETITE_KERNEL32: u16 = 601;
    pub const RECORD_NAME_PETITE_USER32: u16 = 602;
    pub const RECORD_NAME_PEX: u16 = 603;
    pub const RECORD_NAME_PFECX: u16 = 604;
    pub const RECORD_NAME_PGMPAK: u16 = 605;
    pub const RECORD_NAME_PHARLAP: u16 = 606;
    pub const RECORD_NAME_PHOENIXPROTECTOR: u16 = 607;
    pub const RECORD_NAME_PHP: u16 = 608;
    pub const RECORD_NAME_PICRYPTOR: u16 = 609;
    pub const RECORD_NAME_PKLITE: u16 = 610;
    pub const RECORD_NAME_PKLITE32: u16 = 611;
    pub const RECORD_NAME_PKSFX: u16 = 612;
    pub const RECORD_NAME_PKTINY: u16 = 613;
    pub const RECORD_NAME_PKZIPMINISFX: u16 = 614;
    pub const RECORD_NAME_PLAIN: u16 = 615;
    pub const RECORD_NAME_PLEXCLANG: u16 = 616;
    pub const RECORD_NAME_PLMX: u16 = 617;
    pub const RECORD_NAME_PMODEW: u16 = 618;
    pub const RECORD_NAME_PNG: u16 = 619;
    pub const RECORD_NAME_POKECRYPTER: u16 = 620;
    pub const RECORD_NAME_POLYCRYPTPE: u16 = 621;
    pub const RECORD_NAME_POSIX: u16 = 622;
    pub const RECORD_NAME_POWERBASIC: u16 = 623;
    pub const RECORD_NAME_POWERC: u16 = 624;
    pub const RECORD_NAME_PRIVATEEXEPROTECTOR: u16 = 625;
    pub const RECORD_NAME_PROGUARD: u16 = 626;
    pub const RECORD_NAME_PROPACK: u16 = 627;
    pub const RECORD_NAME_PROPASCAL: u16 = 628;
    pub const RECORD_NAME_PROTECTEXE: u16 = 629;
    pub const RECORD_NAME_PSEUDOAPKSIGNER: u16 = 630;
    pub const RECORD_NAME_PUBCRYPTER: u16 = 631;
    pub const RECORD_NAME_PUNISHER: u16 = 632;
    pub const RECORD_NAME_PUREBASIC: u16 = 633;
    pub const RECORD_NAME_PUSSYCRYPTER: u16 = 634;
    pub const RECORD_NAME_PYINSTALLER: u16 = 635;
    pub const RECORD_NAME_PYTHON: u16 = 636;
    pub const RECORD_NAME_QCCOMPILER: u16 = 637;
    pub const RECORD_NAME_QDBH: u16 = 638;
    pub const RECORD_NAME_QIHOO360PROTECTION: u16 = 639;
    pub const RECORD_NAME_QML: u16 = 640;
    pub const RECORD_NAME_QNX: u16 = 641;
    pub const RECORD_NAME_QRYPT0R: u16 = 642;
    pub const RECORD_NAME_QT: u16 = 643;
    pub const RECORD_NAME_QTINSTALLER: u16 = 644;
    pub const RECORD_NAME_QUICKPACKNT: u16 = 645;
    pub const RECORD_NAME_QUICKPASCAL: u16 = 646;
    pub const RECORD_NAME_R8: u16 = 647;
    pub const RECORD_NAME_RADIALIX: u16 = 648;
    pub const RECORD_NAME_RAR: u16 = 649;
    pub const RECORD_NAME_RCRYPTOR: u16 = 650;
    pub const RECORD_NAME_RDGTEJONCRYPTER: u16 = 651;
    pub const RECORD_NAME_REC: u16 = 652;
    pub const RECORD_NAME_REDHATLINUX: u16 = 653;
    pub const RECORD_NAME_RELPACK: u16 = 654;
    pub const RECORD_NAME_RENETPACK: u16 = 655;
    pub const RECORD_NAME_RESOURCE: u16 = 656;
    pub const RECORD_NAME_RESOURCE_CURSOR: u16 = 657;
    pub const RECORD_NAME_RESOURCE_DIALOG: u16 = 658;
    pub const RECORD_NAME_RESOURCE_ICON: u16 = 659;
    pub const RECORD_NAME_RESOURCE_MENU: u16 = 660;
    pub const RECORD_NAME_RESOURCE_STRINGTABLE: u16 = 661;
    pub const RECORD_NAME_RESOURCE_VERSIONINFO: u16 = 662;
    pub const RECORD_NAME_REVPROT: u16 = 663;
    pub const RECORD_NAME_RJCRUSH: u16 = 664;
    pub const RECORD_NAME_RLP: u16 = 665;
    pub const RECORD_NAME_RLPACK: u16 = 666;
    pub const RECORD_NAME_ROGUEPACK: u16 = 667;
    pub const RECORD_NAME_ROSASM: u16 = 668;
    pub const RECORD_NAME_RTF: u16 = 669;
    pub const RECORD_NAME_RTLINK: u16 = 670;
    pub const RECORD_NAME_RTPATCH: u16 = 671;
    pub const RECORD_NAME_RUBY: u16 = 672;
    pub const RECORD_NAME_RUST: u16 = 673;
    pub const RECORD_NAME_SAFEENGINELLVM: u16 = 674;
    pub const RECORD_NAME_SAFEENGINESHIELDEN: u16 = 675;
    pub const RECORD_NAME_SANDHOOK: u16 = 676;
    pub const RECORD_NAME_SBASIC: u16 = 677;
    pub const RECORD_NAME_SCOBFUSCATOR: u16 = 678;
    pub const RECORD_NAME_SCPACK: u16 = 679;
    pub const RECORD_NAME_SCRNCH: u16 = 680;
    pub const RECORD_NAME_SDPROTECTORPRO: u16 = 681;
    pub const RECORD_NAME_SECNEO: u16 = 682;
    pub const RECORD_NAME_SECSHELL: u16 = 683;
    pub const RECORD_NAME_SECURESHADE: u16 = 684;
    pub const RECORD_NAME_SECUROM: u16 = 685;
    pub const RECORD_NAME_SEPOS: u16 = 686;
    pub const RECORD_NAME_SERGREENAPPACKER: u16 = 687;
    pub const RECORD_NAME_SETUPFACTORY: u16 = 688;
    pub const RECORD_NAME_SETUPSPECIALIST: u16 = 689;
    pub const RECORD_NAME_SEXECRYPTER: u16 = 690;
    pub const RECORD_NAME_SHELL: u16 = 691;
    pub const RECORD_NAME_SHRINKER: u16 = 692;
    pub const RECORD_NAME_SIGNATORY: u16 = 693;
    pub const RECORD_NAME_SIGNUPDATE: u16 = 694;
    pub const RECORD_NAME_SIMBIOZ: u16 = 695;
    pub const RECORD_NAME_SIMCRYPTER: u16 = 696;
    pub const RECORD_NAME_SIMPLECRYPTER: u16 = 697;
    pub const RECORD_NAME_SIMPLEPACK: u16 = 698;
    pub const RECORD_NAME_SINGLEJAR: u16 = 699;
    pub const RECORD_NAME_SIXXPACK: u16 = 700;
    pub const RECORD_NAME_SKATER: u16 = 701;
    pub const RECORD_NAME_SMALLC: u16 = 702;
    pub const RECORD_NAME_SMARTASSEMBLY: u16 = 703;
    pub const RECORD_NAME_SMARTINSTALLMAKER: u16 = 704;
    pub const RECORD_NAME_SMOKESCREENCRYPTER: u16 = 705;
    pub const RECORD_NAME_SNAPDRAGONLLVMARM: u16 = 706;
    pub const RECORD_NAME_SNAPPROTECT: u16 = 707;
    pub const RECORD_NAME_SNOOPCRYPT: u16 = 708;
    pub const RECORD_NAME_SOFTDEFENDER: u16 = 709;
    pub const RECORD_NAME_SOFTSENTRY: u16 = 710;
    pub const RECORD_NAME_SOFTWARECOMPRESS: u16 = 711;
    pub const RECORD_NAME_SOFTWARETOOLWORKSC80: u16 = 712;
    pub const RECORD_NAME_SOFTWAREZATOR: u16 = 713;
    pub const RECORD_NAME_SOLARIS: u16 = 714;
    pub const RECORD_NAME_SOURCERYCODEBENCH: u16 = 715;
    pub const RECORD_NAME_SOURCERYCODEBENCHLITE: u16 = 716;
    pub const RECORD_NAME_SPICESNET: u16 = 717;
    pub const RECORD_NAME_SPIRIT: u16 = 718;
    pub const RECORD_NAME_SPOONINSTALLER: u16 = 719;
    pub const RECORD_NAME_SPOONSTUDIO: u16 = 720;
    pub const RECORD_NAME_SPOONSTUDIO2011: u16 = 721;
    pub const RECORD_NAME_SQUEEZSFX: u16 = 722;
    pub const RECORD_NAME_SQUIRRELINSTALLER: u16 = 723;
    pub const RECORD_NAME_STABSDEBUGINFO: u16 = 724;
    pub const RECORD_NAME_STARFORCE: u16 = 725;
    pub const RECORD_NAME_STARTOSLINUX: u16 = 726;
    pub const RECORD_NAME_STASFODIDOCRYPTOR: u16 = 727;
    pub const RECORD_NAME_STONESPEENCRYPTOR: u16 = 728;
    pub const RECORD_NAME_STONYBROOKPASCAL: u16 = 729;
    pub const RECORD_NAME_SUNOS: u16 = 730;
    pub const RECORD_NAME_SUNWORKSHOP: u16 = 731;
    pub const RECORD_NAME_SUNWORKSHOPCOMPILERS: u16 = 732;
    pub const RECORD_NAME_SUPERSOFTADA: u16 = 733;
    pub const RECORD_NAME_SUPERSOFTC: u16 = 734;
    pub const RECORD_NAME_SUPERSOFTFORTRAN: u16 = 735;
    pub const RECORD_NAME_SUSELINUX: u16 = 736;
    pub const RECORD_NAME_SVKPROTECTOR: u16 = 737;
    pub const RECORD_NAME_SWF: u16 = 738;
    pub const RECORD_NAME_SWIFT: u16 = 739;
    pub const RECORD_NAME_SYLLABLE: u16 = 740;
    pub const RECORD_NAME_SYMBOLTABLE: u16 = 741;
    pub const RECORD_NAME_TAR: u16 = 742;
    pub const RECORD_NAME_TARMAINSTALLER: u16 = 743;
    pub const RECORD_NAME_TCLPASCAL: u16 = 744;
    pub const RECORD_NAME_TELOCK: u16 = 745;
    pub const RECORD_NAME_TENCENTLEGU: u16 = 746;
    pub const RECORD_NAME_TENCENTPROTECTION: u16 = 747;
    pub const RECORD_NAME_TGRCRYPTER: u16 = 748;
    pub const RECORD_NAME_THEBESTCRYPTORBYFSK: u16 = 749;
    pub const RECORD_NAME_THEMIDAWINLICENSE: u16 = 750;
    pub const RECORD_NAME_THEZONECRYPTER: u16 = 751;
    pub const RECORD_NAME_THINSTALL: u16 = 752;
    pub const RECORD_NAME_THUMBC: u16 = 753;
    pub const RECORD_NAME_TIFF: u16 = 754;
    pub const RECORD_NAME_TINYC: u16 = 755;
    pub const RECORD_NAME_TINYPROG: u16 = 756;
    pub const RECORD_NAME_TINYSIGN: u16 = 757;
    pub const RECORD_NAME_TOPSPEED: u16 = 758;
    pub const RECORD_NAME_TOTALCOMMANDERINSTALLER: u16 = 759;
    pub const RECORD_NAME_TPPPACK: u16 = 760;
    pub const RECORD_NAME_TRU64: u16 = 761;
    pub const RECORD_NAME_TSTCRYPTER: u16 = 762;
    pub const RECORD_NAME_TTF: u16 = 763;
    pub const RECORD_NAME_TTPROTECT: u16 = 764;
    pub const RECORD_NAME_TURBOBASIC: u16 = 765;
    pub const RECORD_NAME_TURBOC: u16 = 766;
    pub const RECORD_NAME_TURBOCPP: u16 = 767;
    pub const RECORD_NAME_TURBOLINKER: u16 = 768;
    pub const RECORD_NAME_TURBOLINUX: u16 = 769;
    pub const RECORD_NAME_TURBOPASCAL: u16 = 770;
    pub const RECORD_NAME_TURBOSTUDIO: u16 = 771;
    pub const RECORD_NAME_TURKISHCYBERSIGNATURE: u16 = 772;
    pub const RECORD_NAME_TURKOJANCRYPTER: u16 = 773;
    pub const RECORD_NAME_TVOS: u16 = 774;
    pub const RECORD_NAME_TVOSSDK: u16 = 775;
    pub const RECORD_NAME_UBUNTUCLANG: u16 = 776;
    pub const RECORD_NAME_UBUNTULINUX: u16 = 777;
    pub const RECORD_NAME_UCEXE: u16 = 778;
    pub const RECORD_NAME_UNDERGROUNDCRYPTER: u16 = 779;
    pub const RECORD_NAME_UNDOCRYPTER: u16 = 780;
    pub const RECORD_NAME_UNICODE: u16 = 781;
    pub const RECORD_NAME_UNICOMSDK: u16 = 782;
    pub const RECORD_NAME_UNILINK: u16 = 783;
    pub const RECORD_NAME_UNITY: u16 = 784;
    pub const RECORD_NAME_UNIVERSALTUPLECOMPILER: u16 = 785;
    pub const RECORD_NAME_UNIX: u16 = 786;
    pub const RECORD_NAME_UNKNOWN: u16 = 787;
    pub const RECORD_NAME_UNKNOWN0: u16 = 788;
    pub const RECORD_NAME_UNKNOWN1: u16 = 789;
    pub const RECORD_NAME_UNKNOWN2: u16 = 790;
    pub const RECORD_NAME_UNKNOWN3: u16 = 791;
    pub const RECORD_NAME_UNKNOWN4: u16 = 792;
    pub const RECORD_NAME_UNKNOWN5: u16 = 793;
    pub const RECORD_NAME_UNKNOWN6: u16 = 794;
    pub const RECORD_NAME_UNKNOWN7: u16 = 795;
    pub const RECORD_NAME_UNKNOWN8: u16 = 796;
    pub const RECORD_NAME_UNKNOWN9: u16 = 797;
    pub const RECORD_NAME_UNKOWNCRYPTER: u16 = 798;
    pub const RECORD_NAME_UNK_UPXLIKE: u16 = 799;
    pub const RECORD_NAME_UNOPIX: u16 = 800;
    pub const RECORD_NAME_UPX: u16 = 801;
    pub const RECORD_NAME_UTF8: u16 = 802;
    pub const RECORD_NAME_VALVE: u16 = 803;
    pub const RECORD_NAME_VANVALZAHPASCAL: u16 = 804;
    pub const RECORD_NAME_VBNET: u16 = 805;
    pub const RECORD_NAME_VBSTOEXE: u16 = 806;
    pub const RECORD_NAME_VCASMPROTECTOR: u16 = 807;
    pub const RECORD_NAME_VCL: u16 = 808;
    pub const RECORD_NAME_VCLPACKAGEINFO: u16 = 809;
    pub const RECORD_NAME_VDOG: u16 = 810;
    pub const RECORD_NAME_VERACRYPT: u16 = 811;
    pub const RECORD_NAME_VINELINUX: u16 = 812;
    pub const RECORD_NAME_VIRBOXPROTECTOR: u16 = 813;
    pub const RECORD_NAME_VIRTUALIZEPROTECT: u16 = 814;
    pub const RECORD_NAME_VIRTUALPASCAL: u16 = 815;
    pub const RECORD_NAME_VISE: u16 = 816;
    pub const RECORD_NAME_VISUALBASIC: u16 = 817;
    pub const RECORD_NAME_VISUALCCPP: u16 = 818;
    pub const RECORD_NAME_VISUALCSHARP: u16 = 819;
    pub const RECORD_NAME_VISUALOBJECTS: u16 = 820;
    pub const RECORD_NAME_VMPROTECT: u16 = 821;
    pub const RECORD_NAME_VMUNPACKER: u16 = 822;
    pub const RECORD_NAME_VMWARE: u16 = 823;
    pub const RECORD_NAME_VPACKER: u16 = 824;
    pub const RECORD_NAME_WALLE: u16 = 825;
    pub const RECORD_NAME_WANGZEHUALLVM: u16 = 826;
    pub const RECORD_NAME_WATCHOS: u16 = 827;
    pub const RECORD_NAME_WATCHOSSDK: u16 = 828;
    pub const RECORD_NAME_WATCOMC: u16 = 829;
    pub const RECORD_NAME_WATCOMCCPP: u16 = 830;
    pub const RECORD_NAME_WATCOMDEBUGINFO: u16 = 831;
    pub const RECORD_NAME_WATCOMLINKER: u16 = 832;
    pub const RECORD_NAME_WAV: u16 = 833;
    pub const RECORD_NAME_WDOSX: u16 = 834;
    pub const RECORD_NAME_WEBP: u16 = 835;
    pub const RECORD_NAME_WHITELLCRYPT: u16 = 836;
    pub const RECORD_NAME_WHITESMITHSC: u16 = 837;
    pub const RECORD_NAME_WINACE: u16 = 838;
    pub const RECORD_NAME_WINAUTH: u16 = 839;
    pub const RECORD_NAME_WINDOFCRYPT: u16 = 840;
    pub const RECORD_NAME_WINDOWS: u16 = 841;
    pub const RECORD_NAME_WINDOWSBITMAP: u16 = 842;
    pub const RECORD_NAME_WINDOWSCE: u16 = 843;
    pub const RECORD_NAME_WINDOWSCURSOR: u16 = 844;
    pub const RECORD_NAME_WINDOWSICON: u16 = 845;
    pub const RECORD_NAME_WINDOWSINSTALLER: u16 = 846;
    pub const RECORD_NAME_WINDOWSMEDIA: u16 = 847;
    pub const RECORD_NAME_WINDRIVERLINUX: u16 = 848;
    pub const RECORD_NAME_WINGSCRYPT: u16 = 849;
    pub const RECORD_NAME_WINKRIPT: u16 = 850;
    pub const RECORD_NAME_WINRAR: u16 = 851;
    pub const RECORD_NAME_WINUPACK: u16 = 852;
    pub const RECORD_NAME_WINZIP: u16 = 853;
    pub const RECORD_NAME_WISE: u16 = 854;
    pub const RECORD_NAME_WIXTOOLSET: u16 = 855;
    pub const RECORD_NAME_WLCRYPT: u16 = 856;
    pub const RECORD_NAME_WLGROUPCRYPTER: u16 = 857;
    pub const RECORD_NAME_WOLVERINEPATCHER: u16 = 858;
    pub const RECORD_NAME_WOUTHRSEXECRYPTER: u16 = 859;
    pub const RECORD_NAME_WWPACK: u16 = 860;
    pub const RECORD_NAME_WWPACK32: u16 = 861;
    pub const RECORD_NAME_WXWIDGETS: u16 = 862;
    pub const RECORD_NAME_X86ASSEMBLER: u16 = 863;
    pub const RECORD_NAME_XAR: u16 = 864;
    pub const RECORD_NAME_XBOX: u16 = 865;
    pub const RECORD_NAME_XCODE: u16 = 866;
    pub const RECORD_NAME_XCODELINKER: u16 = 867;
    pub const RECORD_NAME_XCOMP: u16 = 868;
    pub const RECORD_NAME_XENOCODE: u16 = 869;
    pub const RECORD_NAME_XENOCODEPOSTBUILD: u16 = 870;
    pub const RECORD_NAME_XENOCODEPOSTBUILD2009FORDOTNET: u16 = 871;
    pub const RECORD_NAME_XENOCODEPOSTBUILD2010FORDOTNET: u16 = 872;
    pub const RECORD_NAME_XENOCODEVIRTUALAPPLICATIONSTUDIO2009: u16 = 873;
    pub const RECORD_NAME_XENOCODEVIRTUALAPPLICATIONSTUDIO2010: u16 = 874;
    pub const RECORD_NAME_XENOCODEVIRTUALAPPLICATIONSTUDIO2010ISVEDITION: u16 = 875;
    pub const RECORD_NAME_XENOCODEVIRTUALAPPLICATIONSTUDIO2012ISVEDITION: u16 = 876;
    pub const RECORD_NAME_XENOCODEVIRTUALAPPLICATIONSTUDIO2013ISVEDITION: u16 = 877;
    pub const RECORD_NAME_XML: u16 = 878;
    pub const RECORD_NAME_XPACK: u16 = 879;
    pub const RECORD_NAME_XTREAMLOK: u16 = 880;
    pub const RECORD_NAME_XTREMEPROTECTOR: u16 = 881;
    pub const RECORD_NAME_XVOLKOLAK: u16 = 882;
    pub const RECORD_NAME_XZ: u16 = 883;
    pub const RECORD_NAME_YANDEX: u16 = 884;
    pub const RECORD_NAME_YANO: u16 = 885;
    pub const RECORD_NAME_YIDUN: u16 = 886;
    pub const RECORD_NAME_YODASCRYPTER: u16 = 887;
    pub const RECORD_NAME_YODASPROTECTOR: u16 = 888;
    pub const RECORD_NAME_YZPACK: u16 = 889;
    pub const RECORD_NAME_Z80BCPL: u16 = 890;
    pub const RECORD_NAME_ZELDACRYPT: u16 = 891;
    pub const RECORD_NAME_ZIG: u16 = 892;
    pub const RECORD_NAME_ZIP: u16 = 893;
    pub const RECORD_NAME_ZLIB: u16 = 894;
    pub const RECORD_NAME_ZORTECHC: u16 = 895;
    pub const RECORD_NAME_ZPROTECT: u16 = 896;
    pub const RECORD_NAME_LZIP: u16 = 897;
    pub const RECORD_NAME_LZMA: u16 = 898;
    pub const RECORD_NAME_SKATERNET: u16 = 899;
}

pub mod rtype {
    pub const RECORD_TYPE_APKOBFUSCATOR: u8 = 0;
    pub const RECORD_TYPE_APKTOOL: u8 = 1;
    pub const RECORD_TYPE_ARCHIVE: u8 = 2;
    pub const RECORD_TYPE_AUTHOR: u8 = 3;
    pub const RECORD_TYPE_CERTIFICATE: u8 = 4;
    pub const RECORD_TYPE_COMPILER: u8 = 5;
    pub const RECORD_TYPE_COMPRESSOR: u8 = 6;
    pub const RECORD_TYPE_CONVERTER: u8 = 7;
    pub const RECORD_TYPE_CORRUPTEDDATA: u8 = 8;
    pub const RECORD_TYPE_CREATOR: u8 = 9;
    pub const RECORD_TYPE_CRYPTER: u8 = 10;
    pub const RECORD_TYPE_CRYPTOR: u8 = 11;
    pub const RECORD_TYPE_DATA: u8 = 12;
    pub const RECORD_TYPE_DATABASE: u8 = 13;
    pub const RECORD_TYPE_DEBUGDATA: u8 = 14;
    pub const RECORD_TYPE_DOCUMENT: u8 = 15;
    pub const RECORD_TYPE_DONGLEPROTECTION: u8 = 16;
    pub const RECORD_TYPE_DOSEXTENDER: u8 = 17;
    pub const RECORD_TYPE_FORMAT: u8 = 18;
    pub const RECORD_TYPE_GENERIC: u8 = 19;
    pub const RECORD_TYPE_IMAGE: u8 = 20;
    pub const RECORD_TYPE_INSTALLER: u8 = 21;
    pub const RECORD_TYPE_INSTALLERDATA: u8 = 22;
    pub const RECORD_TYPE_JAROBFUSCATOR: u8 = 23;
    pub const RECORD_TYPE_JOINER: u8 = 24;
    pub const RECORD_TYPE_LANGUAGE: u8 = 25;
    pub const RECORD_TYPE_LIBRARY: u8 = 26;
    pub const RECORD_TYPE_LICENSING: u8 = 27;
    pub const RECORD_TYPE_LINKER: u8 = 28;
    pub const RECORD_TYPE_LOADER: u8 = 29;
    pub const RECORD_TYPE_MALWARE: u8 = 30;
    pub const RECORD_TYPE_NETCOMPRESSOR: u8 = 31;
    pub const RECORD_TYPE_NETOBFUSCATOR: u8 = 32;
    pub const RECORD_TYPE_OBFUSCATOR: u8 = 33;
    pub const RECORD_TYPE_OPERATIONSYSTEM: u8 = 34;
    pub const RECORD_TYPE_OVERLAY: u8 = 35;
    pub const RECORD_TYPE_PACKAGE: u8 = 36;
    pub const RECORD_TYPE_PACKER: u8 = 37;
    pub const RECORD_TYPE_PERSONALDATA: u8 = 38;
    pub const RECORD_TYPE_PETOOL: u8 = 39;
    pub const RECORD_TYPE_PLATFORM: u8 = 40;
    pub const RECORD_TYPE_PLAYER: u8 = 41;
    pub const RECORD_TYPE_PRODUCER: u8 = 42;
    pub const RECORD_TYPE_PROTECTION: u8 = 43;
    pub const RECORD_TYPE_PROTECTOR: u8 = 44;
    pub const RECORD_TYPE_PROTECTORDATA: u8 = 45;
    pub const RECORD_TYPE_ROM: u8 = 46;
    pub const RECORD_TYPE_SFX: u8 = 47;
    pub const RECORD_TYPE_SFXDATA: u8 = 48;
    pub const RECORD_TYPE_SIGNTOOL: u8 = 49;
    pub const RECORD_TYPE_SOURCECODE: u8 = 50;
    pub const RECORD_TYPE_STUB: u8 = 51;
    pub const RECORD_TYPE_TOOL: u8 = 52;
    pub const RECORD_TYPE_TROJAN: u8 = 53;
    pub const RECORD_TYPE_UNKNOWN: u8 = 54;
    pub const RECORD_TYPE_VIRTUALMACHINE: u8 = 55;
    pub const RECORD_TYPE_VIRUS: u8 = 56;
}

pub mod ft {
    pub const FT_7Z: u16 = 0;
    pub const FT_ACE: u16 = 1;
    pub const FT_ACESFX: u16 = 2;
    pub const FT_AGIS: u16 = 3;
    pub const FT_AIN: u16 = 4;
    pub const FT_AIX_BFF: u16 = 5;
    pub const FT_AIX_BIGAF: u16 = 6;
    pub const FT_ALDUS: u16 = 7;
    pub const FT_ALZ: u16 = 8;
    pub const FT_AMIGAHUNK: u16 = 9;
    pub const FT_AMIGA_ADF: u16 = 10;
    pub const FT_AMIGA_LZX: u16 = 11;
    pub const FT_AMPK: u16 = 12;
    pub const FT_ANDROIDASRC: u16 = 13;
    pub const FT_ANDROIDXML: u16 = 14;
    pub const FT_ANDROID_BOOT: u16 = 15;
    pub const FT_AODOS: u16 = 16;
    pub const FT_AP4: u16 = 17;
    pub const FT_APK: u16 = 18;
    pub const FT_APKS: u16 = 19;
    pub const FT_APPLESINGLE: u16 = 20;
    pub const FT_APPLE_2IMG: u16 = 21;
    pub const FT_APRICOT: u16 = 22;
    pub const FT_AR: u16 = 23;
    pub const FT_ARC: u16 = 24;
    pub const FT_ARCFS: u16 = 25;
    pub const FT_ARCHIVE: u16 = 26;
    pub const FT_ARCSFX: u16 = 27;
    pub const FT_ARCV: u16 = 28;
    pub const FT_ARCV2: u16 = 29;
    pub const FT_ARCV2SFX: u16 = 30;
    pub const FT_ARCV4: u16 = 31;
    pub const FT_ARDI1_SFX: u16 = 32;
    pub const FT_ARDI2_SFX: u16 = 33;
    pub const FT_ARJ: u16 = 34;
    pub const FT_ARJSFX: u16 = 35;
    pub const FT_ARNI_SFX: u16 = 36;
    pub const FT_ARQ: u16 = 37;
    pub const FT_ARQSFX: u16 = 38;
    pub const FT_ARTIPACK: u16 = 39;
    pub const FT_ARX: u16 = 40;
    pub const FT_AR_PDP11: u16 = 41;
    pub const FT_ASAR: u16 = 42;
    pub const FT_ASCEND: u16 = 43;
    pub const FT_ASCEND_BACKUP: u16 = 44;
    pub const FT_ASH0: u16 = 45;
    pub const FT_ASYMETRIX: u16 = 46;
    pub const FT_ASYMETRIXSFX: u16 = 47;
    pub const FT_ATARIST: u16 = 48;
    pub const FT_AUDIO: u16 = 49;
    pub const FT_AVI: u16 = 50;
    pub const FT_BCM: u16 = 51;
    pub const FT_BEOS_PACKAGE: u16 = 52;
    pub const FT_BIGF: u16 = 53;
    pub const FT_BINARY: u16 = 54;
    pub const FT_BINARY16: u16 = 55;
    pub const FT_BINARY2: u16 = 56;
    pub const FT_BINARY32: u16 = 57;
    pub const FT_BINARY64: u16 = 58;
    pub const FT_BINHEX: u16 = 59;
    pub const FT_BINSH_SFX: u16 = 60;
    pub const FT_BLUEBYTE_LIB: u16 = 61;
    pub const FT_BMP: u16 = 62;
    pub const FT_BOHEMIA_PBO: u16 = 63;
    pub const FT_BOO: u16 = 64;
    pub const FT_BORLAND_PACK: u16 = 65;
    pub const FT_BROTLI: u16 = 66;
    pub const FT_BSN: u16 = 67;
    pub const FT_BSNSFX: u16 = 68;
    pub const FT_BTH_PAK: u16 = 69;
    pub const FT_BTOA: u16 = 70;
    pub const FT_BUILD_GRP: u16 = 71;
    pub const FT_BVRP_PAC: u16 = 72;
    pub const FT_BWCF: u16 = 73;
    pub const FT_BWDOS16M: u16 = 74;
    pub const FT_BWF: u16 = 75;
    pub const FT_BZIP1: u16 = 76;
    pub const FT_BZIP2: u16 = 77;
    pub const FT_BZIP2SFX: u16 = 78;
    pub const FT_C64WRAPTOR: u16 = 79;
    pub const FT_C64_T64: u16 = 80;
    pub const FT_CAB: u16 = 81;
    pub const FT_CABSFX: u16 = 82;
    pub const FT_CFBF: u16 = 83;
    pub const FT_CFBF_MSI: u16 = 84;
    pub const FT_CFBF_WIX: u16 = 85;
    pub const FT_CFL: u16 = 86;
    pub const FT_CHIEFLZ: u16 = 87;
    pub const FT_CHIEFLZMULTI: u16 = 88;
    pub const FT_CHM: u16 = 89;
    pub const FT_CHZ: u16 = 90;
    pub const FT_CISO: u16 = 91;
    pub const FT_CKP: u16 = 92;
    pub const FT_CLAY: u16 = 93;
    pub const FT_CLI_ASSEMBLY: u16 = 94;
    pub const FT_CLOOP: u16 = 95;
    pub const FT_CLP: u16 = 96;
    pub const FT_CMP_ARCHIVE: u16 = 97;
    pub const FT_COM: u16 = 98;
    pub const FT_COMPACT_PRO: u16 = 99;
    pub const FT_COMPAQ_LZH: u16 = 100;
    pub const FT_COMPRESS: u16 = 101;
    pub const FT_COPYQM: u16 = 102;
    pub const FT_COREL_LTEC: u16 = 103;
    pub const FT_CPIO: u16 = 104;
    pub const FT_CPM_CRUNCH: u16 = 105;
    pub const FT_CPM_LBR: u16 = 106;
    pub const FT_CPM_LZH: u16 = 107;
    pub const FT_CREATEINSTALL_SFX: u16 = 108;
    pub const FT_CRU: u16 = 109;
    pub const FT_CUR: u16 = 110;
    pub const FT_DATA: u16 = 111;
    pub const FT_DEARK_LEGACY_ARCHIVE: u16 = 112;
    pub const FT_DEB: u16 = 113;
    pub const FT_DER: u16 = 114;
    pub const FT_DESCENT_HOG: u16 = 115;
    pub const FT_DESCENT_HOG2: u16 = 116;
    pub const FT_DEX: u16 = 117;
    pub const FT_DISKJUGGLER_CDI: u16 = 118;
    pub const FT_DISK_DOUBLER: u16 = 119;
    pub const FT_DISK_DOUBLER_DDA2: u16 = 120;
    pub const FT_DISK_DOUBLER_DDAR: u16 = 121;
    pub const FT_DJVU: u16 = 122;
    pub const FT_DMA: u16 = 123;
    pub const FT_DMA_PACK: u16 = 124;
    pub const FT_DMG: u16 = 125;
    pub const FT_DMS: u16 = 126;
    pub const FT_DN_ARCHIVE: u16 = 127;
    pub const FT_DOCUMENT: u16 = 128;
    pub const FT_DOOM_WAD: u16 = 129;
    pub const FT_DOS16M: u16 = 130;
    pub const FT_DOS4G: u16 = 131;
    pub const FT_DPK: u16 = 132;
    pub const FT_DSKEXP: u16 = 133;
    pub const FT_DSL2: u16 = 134;
    pub const FT_DTC: u16 = 135;
    pub const FT_DT_PACK: u16 = 136;
    pub const FT_EA: u16 = 137;
    pub const FT_EALIB: u16 = 138;
    pub const FT_EA_BIG: u16 = 139;
    pub const FT_EA_REFPACK: u16 = 140;
    pub const FT_ECM: u16 = 141;
    pub const FT_ECM_PACK: u16 = 142;
    pub const FT_EDC_PACKED: u16 = 143;
    pub const FT_EDP: u16 = 144;
    pub const FT_ELF: u16 = 145;
    pub const FT_ELF32: u16 = 146;
    pub const FT_ELF32_CABSFX: u16 = 147;
    pub const FT_ELF32_FREEARCSFX: u16 = 148;
    pub const FT_ELF32_RARSFX: u16 = 149;
    pub const FT_ELF32_SFX: u16 = 150;
    pub const FT_ELF32_ZIPSFX: u16 = 151;
    pub const FT_ELF32_ZPAQSFX: u16 = 152;
    pub const FT_ELF64: u16 = 153;
    pub const FT_ELF64_CABSFX: u16 = 154;
    pub const FT_ELF64_FREEARCSFX: u16 = 155;
    pub const FT_ELF64_RARSFX: u16 = 156;
    pub const FT_ELF64_SFX: u16 = 157;
    pub const FT_ELF64_ZIPSFX: u16 = 158;
    pub const FT_ELF64_ZPAQSFX: u16 = 159;
    pub const FT_EML: u16 = 160;
    pub const FT_EMT_IMAGE: u16 = 161;
    pub const FT_EPFS_ARCHIVE: u16 = 162;
    pub const FT_EPSF_SFX: u16 = 163;
    pub const FT_ESP: u16 = 164;
    pub const FT_EXE_EBOOKCREATOR: u16 = 165;
    pub const FT_EXE_SBOOKBUILDER: u16 = 166;
    pub const FT_FDI: u16 = 167;
    pub const FT_FINEREADER_PACK: u16 = 168;
    pub const FT_FINSTALL_ARCHIVE: u16 = 169;
    pub const FT_FIZ: u16 = 170;
    pub const FT_FLD: u16 = 171;
    pub const FT_FLS: u16 = 172;
    pub const FT_FMC1: u16 = 173;
    pub const FT_FPAK: u16 = 174;
    pub const FT_FREEARC: u16 = 175;
    pub const FT_FREEARCSFX: u16 = 176;
    pub const FT_FREEZE: u16 = 177;
    pub const FT_FRONTPAGE_THEME: u16 = 178;
    pub const FT_FTCOMP: u16 = 179;
    pub const FT_GAMOS: u16 = 180;
    pub const FT_GAS_HUFF: u16 = 181;
    pub const FT_GENIUS_LIBRARY: u16 = 182;
    pub const FT_GENTEE: u16 = 183;
    pub const FT_GETTEXT_MO: u16 = 184;
    pub const FT_GIF: u16 = 185;
    pub const FT_GIT_OBJECT: u16 = 186;
    pub const FT_GKSETUP: u16 = 187;
    pub const FT_GLU: u16 = 188;
    pub const FT_GOB: u16 = 189;
    pub const FT_GOB2: u16 = 190;
    pub const FT_GODOT_PCK: u16 = 191;
    pub const FT_GPFPACK: u16 = 192;
    pub const FT_GPINSTALL_SFX: u16 = 193;
    pub const FT_GST_PACK: u16 = 194;
    pub const FT_GTU: u16 = 195;
    pub const FT_GZIP: u16 = 196;
    pub const FT_GZIPSFX: u16 = 197;
    pub const FT_HA: u16 = 198;
    pub const FT_HAP: u16 = 199;
    pub const FT_HDCOPY: u16 = 200;
    pub const FT_HE_TLKB: u16 = 201;
    pub const FT_HFE: u16 = 202;
    pub const FT_HLB: u16 = 203;
    pub const FT_HUFF: u16 = 204;
    pub const FT_HZL: u16 = 205;
    pub const FT_IBM_SPACK: u16 = 206;
    pub const FT_IBM_ZPAK: u16 = 207;
    pub const FT_ICC: u16 = 208;
    pub const FT_ICO: u16 = 209;
    pub const FT_IGF1: u16 = 210;
    pub const FT_IGF2: u16 = 211;
    pub const FT_IMAGE: u16 = 212;
    pub const FT_IMP: u16 = 213;
    pub const FT_INFOGRAMES_PAK: u16 = 214;
    pub const FT_INNOSETUP: u16 = 215;
    pub const FT_INSA: u16 = 216;
    pub const FT_INSTALIT_DATA: u16 = 217;
    pub const FT_INSTALIT_SFX: u16 = 218;
    pub const FT_INSTALL4J_SFX: u16 = 219;
    pub const FT_INSTALLANYWHERE_SFX: u16 = 220;
    pub const FT_INSTALLSHIELD3_ARCHIVE: u16 = 221;
    pub const FT_INSTALLSHIELD3_SFX: u16 = 222;
    pub const FT_INSTALLSHIELD_BOOT: u16 = 223;
    pub const FT_INSTALLSHIELD_LAUNCHER: u16 = 224;
    pub const FT_INTEDU_FT: u16 = 225;
    pub const FT_IPA: u16 = 226;
    pub const FT_IRIX_SA: u16 = 227;
    pub const FT_IRWINPAC: u16 = 228;
    pub const FT_IS11: u16 = 229;
    pub const FT_IS14_SFX: u16 = 230;
    pub const FT_IS7_INX: u16 = 231;
    pub const FT_ISCAB: u16 = 232;
    pub const FT_ISO9660: u16 = 233;
    pub const FT_ISSETUPSTREAM: u16 = 234;
    pub const FT_IS_SKIN: u16 = 235;
    pub const FT_IS_STORED: u16 = 236;
    pub const FT_IVT: u16 = 237;
    pub const FT_IZPACK: u16 = 238;
    pub const FT_JAM: u16 = 239;
    pub const FT_JAR: u16 = 240;
    pub const FT_JASC_ARCHIVE: u16 = 241;
    pub const FT_JAVACLASS: u16 = 242;
    pub const FT_JBF: u16 = 243;
    pub const FT_JETBBS: u16 = 244;
    pub const FT_JGPAK: u16 = 245;
    pub const FT_JM93: u16 = 246;
    pub const FT_JPEG: u16 = 247;
    pub const FT_KA_ARCHIVE: u16 = 248;
    pub const FT_KBOOM: u16 = 249;
    pub const FT_KOLIBRI_KPACK: u16 = 250;
    pub const FT_KRML: u16 = 251;
    pub const FT_KWAJ: u16 = 252;
    pub const FT_KWAJSFX: u16 = 253;
    pub const FT_LARC_PFX: u16 = 254;
    pub const FT_LBR_COBOL: u16 = 255;
    pub const FT_LE: u16 = 256;
    pub const FT_LEGACY_CAT: u16 = 257;
    pub const FT_LEGACY_RES: u16 = 258;
    pub const FT_LEGACY_RSC: u16 = 259;
    pub const FT_LHA: u16 = 260;
    pub const FT_LHASFX: u16 = 261;
    pub const FT_LIBDSK_IMAGE: u16 = 262;
    pub const FT_LIF_COMPRESSED: u16 = 263;
    pub const FT_LIM: u16 = 264;
    pub const FT_LIZARD: u16 = 265;
    pub const FT_LOFI: u16 = 266;
    pub const FT_LOGITECH_COMPRESS: u16 = 267;
    pub const FT_LPAK: u16 = 268;
    pub const FT_LPAQ8: u16 = 269;
    pub const FT_LSZ: u16 = 270;
    pub const FT_LX: u16 = 271;
    pub const FT_LZ4: u16 = 272;
    pub const FT_LZ5: u16 = 273;
    pub const FT_LZDIET: u16 = 274;
    pub const FT_LZHCXP: u16 = 275;
    pub const FT_LZIP: u16 = 276;
    pub const FT_LZMA: u16 = 277;
    pub const FT_LZO: u16 = 278;
    pub const FT_LZPIS2: u16 = 279;
    pub const FT_LZV1: u16 = 280;
    pub const FT_LZWD: u16 = 281;
    pub const FT_MACBINARY: u16 = 282;
    pub const FT_MACHO: u16 = 283;
    pub const FT_MACHO32: u16 = 284;
    pub const FT_MACHO64: u16 = 285;
    pub const FT_MACHOFAT: u16 = 286;
    pub const FT_MAKESELF: u16 = 287;
    pub const FT_MARC: u16 = 288;
    pub const FT_MATHCAD_PACK: u16 = 289;
    pub const FT_MAXIS_MXS: u16 = 290;
    pub const FT_MBOX: u16 = 291;
    pub const FT_MDH: u16 = 292;
    pub const FT_MEGATECH_VOL: u16 = 293;
    pub const FT_MHTML: u16 = 294;
    pub const FT_MI10: u16 = 295;
    pub const FT_MINIDUMP: u16 = 296;
    pub const FT_MIZ: u16 = 297;
    pub const FT_MLB_ARCHIVE: u16 = 298;
    pub const FT_MP3: u16 = 299;
    pub const FT_MP4: u16 = 300;
    pub const FT_MPQ: u16 = 301;
    pub const FT_MSCOMPRESS_SZ: u16 = 302;
    pub const FT_MSDOS: u16 = 303;
    pub const FT_MSDOS_COPYQM: u16 = 304;
    pub const FT_MTREE: u16 = 305;
    pub const FT_MUS: u16 = 306;
    pub const FT_MVA: u16 = 307;
    pub const FT_MWAVE_Z: u16 = 308;
    pub const FT_NE: u16 = 309;
    pub const FT_NERO_NRG: u16 = 310;
    pub const FT_NETWARE_PACK: u16 = 311;
    pub const FT_NETWARE_PACK2: u16 = 312;
    pub const FT_NEXTSTEP_DISKIMAGE: u16 = 313;
    pub const FT_NID: u16 = 314;
    pub const FT_NOTETAB: u16 = 315;
    pub const FT_NPACK: u16 = 316;
    pub const FT_NPM: u16 = 317;
    pub const FT_NSCRIPTER_NS2: u16 = 318;
    pub const FT_NSCRIPTER_NSA: u16 = 319;
    pub const FT_NSCRIPTER_SAR: u16 = 320;
    pub const FT_NSIS: u16 = 321;
    pub const FT_NTFS: u16 = 322;
    pub const FT_OBFUSCATED_ARCHIVE: u16 = 323;
    pub const FT_OPC: u16 = 324;
    pub const FT_ORACLE_SQUEEZE: u16 = 325;
    pub const FT_PACKIT: u16 = 326;
    pub const FT_PAKLEO: u16 = 327;
    pub const FT_PAL: u16 = 328;
    pub const FT_PALM_PDB: u16 = 329;
    pub const FT_PANORAMA: u16 = 330;
    pub const FT_PAPERPORT: u16 = 331;
    pub const FT_PARSEC_ARCHIVE: u16 = 332;
    pub const FT_PAX: u16 = 333;
    pub const FT_PCINSTALL: u16 = 334;
    pub const FT_PCINSTALL_SFX: u16 = 335;
    pub const FT_PCM: u16 = 336;
    pub const FT_PCOMM_OS2: u16 = 337;
    pub const FT_PC_SECURE: u16 = 338;
    pub const FT_PDB: u16 = 339;
    pub const FT_PDF: u16 = 340;
    pub const FT_PE: u16 = 341;
    pub const FT_PE32: u16 = 342;
    pub const FT_PE32_7ZSFX: u16 = 343;
    pub const FT_PE32_ACTUALINSTALLER: u16 = 344;
    pub const FT_PE32_ADVANCEDINSTALLER: u16 = 345;
    pub const FT_PE32_ASPACK: u16 = 346;
    pub const FT_PE32_AUTOIT: u16 = 347;
    pub const FT_PE32_BOXEDAPP: u16 = 348;
    pub const FT_PE32_CABSFX: u16 = 349;
    pub const FT_PE32_CLICKTEAM: u16 = 350;
    pub const FT_PE32_CREATEINSTALL: u16 = 351;
    pub const FT_PE32_ENIGMAVB: u16 = 352;
    pub const FT_PE32_FREEARCSFX: u16 = 353;
    pub const FT_PE32_FSG: u16 = 354;
    pub const FT_PE32_IEXPRESS: u16 = 355;
    pub const FT_PE32_INNOSETUP: u16 = 356;
    pub const FT_PE32_INSTALLFORGE: u16 = 357;
    pub const FT_PE32_INSTALLSHIELD: u16 = 358;
    pub const FT_PE32_INSTALLSIMPLE: u16 = 359;
    pub const FT_PE32_JUGGLOR: u16 = 360;
    pub const FT_PE32_MEW: u16 = 361;
    pub const FT_PE32_NSIS: u16 = 362;
    pub const FT_PE32_NSPACK: u16 = 363;
    pub const FT_PE32_PETITE: u16 = 364;
    pub const FT_PE32_PFTW: u16 = 365;
    pub const FT_PE32_RARSFX: u16 = 366;
    pub const FT_PE32_SETUPFACTORY: u16 = 367;
    pub const FT_PE32_SFX: u16 = 368;
    pub const FT_PE32_SMARTINSTALL: u16 = 369;
    pub const FT_PE32_TARMA: u16 = 370;
    pub const FT_PE32_UPX: u16 = 371;
    pub const FT_PE32_WINRARSFX: u16 = 372;
    pub const FT_PE32_WIXBURN: u16 = 373;
    pub const FT_PE32_YODA: u16 = 374;
    pub const FT_PE32_ZIPSFX: u16 = 375;
    pub const FT_PE32_ZPAQSFX: u16 = 376;
    pub const FT_PE64: u16 = 377;
    pub const FT_PE64_7ZSFX: u16 = 378;
    pub const FT_PE64_ACTUALINSTALLER: u16 = 379;
    pub const FT_PE64_ADVANCEDINSTALLER: u16 = 380;
    pub const FT_PE64_AUTOIT: u16 = 381;
    pub const FT_PE64_BOXEDAPP: u16 = 382;
    pub const FT_PE64_CABSFX: u16 = 383;
    pub const FT_PE64_CLICKTEAM: u16 = 384;
    pub const FT_PE64_CREATEINSTALL: u16 = 385;
    pub const FT_PE64_ENIGMAVB: u16 = 386;
    pub const FT_PE64_FREEARCSFX: u16 = 387;
    pub const FT_PE64_IEXPRESS: u16 = 388;
    pub const FT_PE64_INNOSETUP: u16 = 389;
    pub const FT_PE64_INSTALLFORGE: u16 = 390;
    pub const FT_PE64_INSTALLSHIELD: u16 = 391;
    pub const FT_PE64_INSTALLSIMPLE: u16 = 392;
    pub const FT_PE64_NSIS: u16 = 393;
    pub const FT_PE64_PFTW: u16 = 394;
    pub const FT_PE64_RARSFX: u16 = 395;
    pub const FT_PE64_SETUPFACTORY: u16 = 396;
    pub const FT_PE64_SFX: u16 = 397;
    pub const FT_PE64_SMARTINSTALL: u16 = 398;
    pub const FT_PE64_TARMA: u16 = 399;
    pub const FT_PE64_UPX: u16 = 400;
    pub const FT_PE64_WINRARSFX: u16 = 401;
    pub const FT_PE64_WIXBURN: u16 = 402;
    pub const FT_PE64_ZIPSFX: u16 = 403;
    pub const FT_PE64_ZPAQSFX: u16 = 404;
    pub const FT_PEA: u16 = 405;
    pub const FT_PIMP_SFX: u16 = 406;
    pub const FT_PKT: u16 = 407;
    pub const FT_PLAINTEXT: u16 = 408;
    pub const FT_PMA: u16 = 409;
    pub const FT_PMM: u16 = 410;
    pub const FT_PM_DISKCOPY: u16 = 411;
    pub const FT_PNG: u16 = 412;
    pub const FT_POVLAB_LZH: u16 = 413;
    pub const FT_POWERARC: u16 = 414;
    pub const FT_POWERBOARD_BBS: u16 = 415;
    pub const FT_PP20: u16 = 416;
    pub const FT_PRINTSHOP_DELUXE: u16 = 417;
    pub const FT_PROCESS: u16 = 418;
    pub const FT_PSN_COMPRESS: u16 = 419;
    pub const FT_PYC: u16 = 420;
    pub const FT_PYINSTALLER_PYZ: u16 = 421;
    pub const FT_PYINSTALLER_SFX: u16 = 422;
    pub const FT_QCOW2: u16 = 423;
    pub const FT_QDA: u16 = 424;
    pub const FT_QDECK_QIP: u16 = 425;
    pub const FT_QIP1: u16 = 426;
    pub const FT_QNX_BASE: u16 = 427;
    pub const FT_QSETUP: u16 = 428;
    pub const FT_QT_QM: u16 = 429;
    pub const FT_QUAKE_PAK: u16 = 430;
    pub const FT_QUALITAS: u16 = 431;
    pub const FT_QUANTUM: u16 = 432;
    pub const FT_RAR: u16 = 433;
    pub const FT_RARSFX: u16 = 434;
    pub const FT_RAW_LZW15V: u16 = 435;
    pub const FT_RCF: u16 = 436;
    pub const FT_RECOGNITA: u16 = 437;
    pub const FT_REGION: u16 = 438;
    pub const FT_RENPY_RPA: u16 = 439;
    pub const FT_RESOURCE_FORK: u16 = 440;
    pub const FT_RGSSAD: u16 = 441;
    pub const FT_RIB: u16 = 442;
    pub const FT_RID: u16 = 443;
    pub const FT_RIFF: u16 = 444;
    pub const FT_RIVERSOFT: u16 = 445;
    pub const FT_RNC: u16 = 446;
    pub const FT_ROMFS: u16 = 447;
    pub const FT_ROMPAQ: u16 = 448;
    pub const FT_RPGMV_RESOURCE: u16 = 449;
    pub const FT_RPM: u16 = 450;
    pub const FT_RSVK: u16 = 451;
    pub const FT_RTA: u16 = 452;
    pub const FT_RTASFX: u16 = 453;
    pub const FT_RTPATCH: u16 = 454;
    pub const FT_RTPATCHSFX: u16 = 455;
    pub const FT_RVZ: u16 = 456;
    pub const FT_RZIP: u16 = 457;
    pub const FT_SABDU_IMAGE: u16 = 458;
    pub const FT_SAF: u16 = 459;
    pub const FT_SAR: u16 = 460;
    pub const FT_SBX_SFX: u16 = 461;
    pub const FT_SCF: u16 = 462;
    pub const FT_SCI: u16 = 463;
    pub const FT_SCL: u16 = 464;
    pub const FT_SEA_DATA: u16 = 465;
    pub const FT_SECOND_NATURE: u16 = 466;
    pub const FT_SETTLERS_FT: u16 = 467;
    pub const FT_SFPACK: u16 = 468;
    pub const FT_SFXGZIP: u16 = 469;
    pub const FT_SHAR: u16 = 470;
    pub const FT_SHRINKWRAP_IMAGE: u16 = 471;
    pub const FT_SIGNATURE: u16 = 472;
    pub const FT_SILMARILS: u16 = 473;
    pub const FT_SLS: u16 = 474;
    pub const FT_SM8: u16 = 475;
    pub const FT_SMSIPAK: u16 = 476;
    pub const FT_SND: u16 = 477;
    pub const FT_SOFTPAQ1_SFX: u16 = 478;
    pub const FT_SOFTPAQ_2: u16 = 479;
    pub const FT_SOFTRONICS: u16 = 480;
    pub const FT_SOLARIS_BOOT: u16 = 481;
    pub const FT_SOLARIS_PKG: u16 = 482;
    pub const FT_SOLITAIRE_DELUXE: u16 = 483;
    pub const FT_SOS: u16 = 484;
    pub const FT_SPIS: u16 = 485;
    pub const FT_SPISSFX: u16 = 486;
    pub const FT_SQ: u16 = 487;
    pub const FT_SQLITE: u16 = 488;
    pub const FT_SQUASHFS: u16 = 489;
    pub const FT_SQX: u16 = 490;
    pub const FT_SQZ: u16 = 491;
    pub const FT_SQZSFX: u16 = 492;
    pub const FT_SSBOB: u16 = 493;
    pub const FT_SSM_MODULE: u16 = 494;
    pub const FT_STK: u16 = 495;
    pub const FT_STORK: u16 = 496;
    pub const FT_STUNTS_DSI: u16 = 497;
    pub const FT_STYLUS: u16 = 498;
    pub const FT_SW: u16 = 499;
    pub const FT_SWAG: u16 = 500;
    pub const FT_SWAG_PACKET: u16 = 501;
    pub const FT_SYDEX_SFX: u16 = 502;
    pub const FT_SZDD: u16 = 503;
    pub const FT_SZDDSFX: u16 = 504;
    pub const FT_TAR: u16 = 505;
    pub const FT_TARNEXTSTEP: u16 = 506;
    pub const FT_TARX1: u16 = 507;
    pub const FT_TARX2: u16 = 508;
    pub const FT_TAR_BZIP2: u16 = 509;
    pub const FT_TAR_GZ: u16 = 510;
    pub const FT_TAR_LZ4: u16 = 511;
    pub const FT_TAR_LZIP: u16 = 512;
    pub const FT_TAR_LZMA: u16 = 513;
    pub const FT_TAR_LZOP: u16 = 514;
    pub const FT_TAR_XZ: u16 = 515;
    pub const FT_TAR_Z: u16 = 516;
    pub const FT_TAR_ZSTD: u16 = 517;
    pub const FT_TEACY: u16 = 518;
    pub const FT_TELEDISK: u16 = 519;
    pub const FT_TERSE: u16 = 520;
    pub const FT_TEXT: u16 = 521;
    pub const FT_TGCF: u16 = 522;
    pub const FT_TGCFSFX: u16 = 523;
    pub const FT_TI99ARC: u16 = 524;
    pub const FT_TIFF: u16 = 525;
    pub const FT_TIVOLI: u16 = 526;
    pub const FT_TNEF: u16 = 527;
    pub const FT_TOPSPEED: u16 = 528;
    pub const FT_TPS: u16 = 529;
    pub const FT_TPWM: u16 = 530;
    pub const FT_TRC: u16 = 531;
    pub const FT_TRCPAK: u16 = 532;
    pub const FT_TRDOS: u16 = 533;
    pub const FT_TTF: u16 = 534;
    pub const FT_TWS: u16 = 535;
    pub const FT_UDF: u16 = 536;
    pub const FT_ULEAD: u16 = 537;
    pub const FT_UNICODE: u16 = 538;
    pub const FT_UNICODE_BE: u16 = 539;
    pub const FT_UNICODE_LE: u16 = 540;
    pub const FT_UNIX_COMPACT: u16 = 541;
    pub const FT_UNIX_PACK: u16 = 542;
    pub const FT_UNKNOWN: u16 = 543;
    pub const FT_UPX: u16 = 544;
    pub const FT_UTF8: u16 = 545;
    pub const FT_UU: u16 = 546;
    pub const FT_VDI: u16 = 547;
    pub const FT_VHD: u16 = 548;
    pub const FT_VHDX: u16 = 549;
    pub const FT_VIDEO: u16 = 550;
    pub const FT_VISE_SFX: u16 = 551;
    pub const FT_VMARC: u16 = 552;
    pub const FT_VMDK: u16 = 553;
    pub const FT_VMSDATABASE: u16 = 554;
    pub const FT_VMSPCSI: u16 = 555;
    pub const FT_VMSSAVESET: u16 = 556;
    pub const FT_WARC: u16 = 557;
    pub const FT_WARPIN: u16 = 558;
    pub const FT_WASM: u16 = 559;
    pub const FT_WAV: u16 = 560;
    pub const FT_WBFS: u16 = 561;
    pub const FT_WEBP: u16 = 562;
    pub const FT_WII_LZ77: u16 = 563;
    pub const FT_WII_U8: u16 = 564;
    pub const FT_WII_WAD: u16 = 565;
    pub const FT_WIM: u16 = 566;
    pub const FT_WINTERMUTE_DCP: u16 = 567;
    pub const FT_WINTERSOFT: u16 = 568;
    pub const FT_WISE_SFX: u16 = 569;
    pub const FT_WOLF_VSWAP: u16 = 570;
    pub const FT_WPK: u16 = 571;
    pub const FT_X64: u16 = 572;
    pub const FT_XAR: u16 = 573;
    pub const FT_XEDITPACK: u16 = 574;
    pub const FT_XM: u16 = 575;
    pub const FT_XML: u16 = 576;
    pub const FT_XPAK: u16 = 577;
    pub const FT_XZ: u16 = 578;
    pub const FT_YENC: u16 = 579;
    pub const FT_ZAP: u16 = 580;
    pub const FT_ZCMP: u16 = 581;
    pub const FT_ZFSF: u16 = 582;
    pub const FT_ZIE: u16 = 583;
    pub const FT_ZIP: u16 = 584;
    pub const FT_ZIPSFX: u16 = 585;
    pub const FT_ZLIB: u16 = 586;
    pub const FT_ZLWB: u16 = 587;
    pub const FT_ZOO: u16 = 588;
    pub const FT_ZOOM: u16 = 589;
    pub const FT_ZPAK: u16 = 590;
    pub const FT_ZPAK_SFX: u16 = 591;
    pub const FT_ZPAQ: u16 = 592;
    pub const FT_ZPAQSFX: u16 = 593;
    pub const FT_ZSTD: u16 = 594;
    pub const FT_ZTC: u16 = 595;
    pub const FT_ZXZIP: u16 = 596;
    pub const FT_ZZ: u16 = 597;
    pub const FT_ZZZ: u16 = 598;
}
