//! Phase 23 regression tests: behaviors pinned against the upstream
//! DIE-engine oracle (`tools/nfd-oracle`). Each test mirrors a diff that
//! was observed and fixed during the differential-convergence pass.

use diec_nfd::{Detection, ScanOptions, scan, sniff_ft};

fn corpus(name: &str) -> Vec<u8> {
    let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus")
        .join(name);
    std::fs::read(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

/// Options matching the oracle harness: deep + heuristic + verbose +
/// recursive + archives + overlay, non-aggressive, non-all-types.
fn oracle_opts() -> ScanOptions {
    ScanOptions {
        deep_scan: true,
        heuristic_scan: true,
        verbose: true,
        all_types: false,
        archives_scan: true,
        recursive_scan: true,
        resources_scan: true,
        overlay_scan: true,
        aggressive_scan: false,
    }
}

fn run(name: &str) -> Vec<Detection> {
    let d = corpus(name);
    let ft = sniff_ft(&d);
    scan(&d, ft, oracle_opts())
}

fn has(out: &[Detection], rtype: &str, name_part: &str) -> bool {
    out.iter()
        .any(|r| r.record_type == rtype && r.record_name.contains(name_part))
}

/// UPX-packed PE: the MinGW/GCC chain is detected through the
/// FT_BINARY overlay signature scan, and `getLanguage` folds GCC +
/// MinGW into `C/C++` (upstream `NFD_Binary::getLanguage`).
#[test]
fn upx_packed_emits_mingw_gcc_and_cpp_language() {
    let out = run("upx-pe32-nrv2b.exe");
    assert!(has(&out, "Packer", "UPX"), "{out:?}");
    assert!(has(&out, "Compiler", "GCC"), "{out:?}");
    assert!(has(&out, "Tool", "MinGW"), "{out:?}");
    assert!(has(&out, "Linker", "GNU ld"), "{out:?}");
    assert!(
        out.iter()
            .any(|r| r.record_type == "Language" && r.record_name == "C/C++"),
        "{out:?}"
    );
    // Nested scans must not leak synthetic Unknown records upward.
    assert!(!out.iter().any(|r| r.record_name == "Unknown"), "{out:?}");
}

/// Unpacked MinGW PE: `.debug_info` section name lives in the COFF
/// string table (`/N` references) — resolving it yields DWARF 5.0.
#[test]
fn unpacked_mingw_pe_resolves_coff_strtab_dwarf() {
    let out = run("upx-pe32-lzma.unpacked.exe");
    assert!(
        out.iter().any(|r| r.record_type == "Debug data"
            && r.record_name.contains("DWARF")
            && r.version == "5.0"),
        "{out:?}"
    );
    assert!(has(&out, "Debug data", "MinGW"), "{out:?}");
}

/// Bare EOCD (empty archive): upstream `XZip::isValid` accepts it, so
/// `handle_Container` emits "0 records inspected" with no
/// "central/local headers verified" suffix (that suffix is only added
/// by the strict `handle_ContainerHeader` fallback).
#[test]
fn empty_zip_eocd_is_plain_container_record() {
    let out = run("edge/empty-zip-eocd.bin");
    assert_eq!(out.len(), 1, "{out:?}");
    let r = &out[0];
    assert_eq!(r.record_type, "Format");
    assert_eq!(r.record_name, "ZIP");
    assert_eq!(r.info, "0 records inspected");
}

/// Mach-O: `clang` compiler records map to the `C/C++` language in
/// upstream `getLanguage` (Clang family → CCPP unless Objective-C).
#[test]
fn macho_clang_maps_to_cpp_language() {
    let out = run("minimal.macho");
    assert!(
        out.iter()
            .any(|r| r.record_type == "Language" && r.record_name == "C/C++"),
        "{out:?}"
    );
}

/// Nested ZIP: the ELF member scan (58-byte truncated ELF) must emit
/// the Unix OS record — upstream `read_*` returns zeroes for missing
/// trailing fields rather than rejecting the whole format. Child scans
/// must not leak a synthetic `Unknown` either.
#[test]
fn nested_zip_elf_member_os_record() {
    let out = run("nested-zip-with-pe.zip");
    assert!(
        out.iter()
            .any(|r| r.record_type == "Operation system" && r.record_name == "Unix"),
        "{out:?}"
    );
    assert!(!out.iter().any(|r| r.record_name == "Unknown"), "{out:?}");
}

/// Malformed/minimal NE: upstream enumerates the overlay file part and
/// the overlay sub-scan falls back to a bare `Unknown` record.
#[test]
fn minimal_ne_overlay_unknown() {
    let out = run("minimal-ne.exe");
    assert!(out.iter().any(|r| r.record_name == "Unknown"), "{out:?}");
}

/// Phase 24: `NFDCompression::ancient` — the XAncientDecoder family.
/// Fixtures are generated by `tools/gen_ancient_corpus.py` and verified
/// against the upstream oracle (each emits exactly one Format record).
#[test]
fn tpwm_decodes_and_reports() {
    let out = run("minimal.tpwm");
    assert_eq!(out.len(), 1, "{out:?}");
    let r = &out[0];
    assert_eq!(r.record_type, "Format");
    assert_eq!(r.record_name, "TPWM");
    assert_eq!(
        r.info,
        "TPWM: Turbo Packer, decoded stream verified, 4 bytes unpacked"
    );
}

#[test]
fn unix_pack_decodes_with_trailing_padding() {
    let out = run("minimal.pack");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "pack");
    assert_eq!(
        out[0].info,
        "z: Pack, decoded stream verified, 4 bytes unpacked, 2 trailing bytes permitted as pack padding"
    );
}

#[test]
fn rnc1_new_stream_decodes() {
    let out = run("minimal.rnc1");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "RNC");
    assert_eq!(
        out[0].info,
        "RNC1: Rob Northen RNC1 Compressor, decoded stream verified, 4 bytes unpacked"
    );
}

#[test]
fn rnc2_new_stream_decodes() {
    let out = run("minimal.rnc2");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "RNC");
    assert_eq!(
        out[0].info,
        "RNC2: Rob Northen RNC2 Compressor, decoded stream verified, 1 bytes unpacked"
    );
}

/// Corrupted RNC streams must fail verification rather than panic or
/// mis-detect (truncated stream, bad packed CRC, bad raw CRC).
#[test]
fn rnc_corrupt_inputs_rejected() {
    let good = corpus("minimal.rnc1");
    for cut in [12usize, 18, 20, 25, 29] {
        let d = &good[..cut];
        let ft = sniff_ft(d);
        let out = scan(d, ft, oracle_opts());
        assert!(
            !out.iter().any(|r| r.record_name == "RNC"),
            "cut {cut}: {out:?}"
        );
    }
    // Bad packed CRC at offset 14.
    let mut bad = good.clone();
    bad[14] ^= 0xff;
    let out = scan(&bad, sniff_ft(&bad), oracle_opts());
    assert!(!out.iter().any(|r| r.record_name == "RNC"), "{out:?}");
    // Bad raw CRC at offset 12 (valid packed CRC -> verification path).
    let mut bad = good.clone();
    bad[12] ^= 0xff;
    let out = scan(&bad, sniff_ft(&bad), oracle_opts());
    assert!(!out.iter().any(|r| r.record_name == "RNC"), "{out:?}");
}

/// Phase 47: RNC old variants (12-byte header, backward bit stream with
/// an anchor byte) and locked (encrypted) RNC1-new streams. Fixtures are
/// generated by `tools/gen_p47_corpus.py` and verified against the
/// upstream oracle (`tools/nfd_diff.py`: 5 files, 0 diffs).
#[test]
fn rnc1_old_stream_decodes() {
    let out = run("rnc1-old.rnc1");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "RNC");
    assert_eq!(
        out[0].info,
        "RNC1: Rob Northen RNC1 Compressor (old), decoded stream verified, 4 bytes unpacked"
    );
}

#[test]
fn rnc2_old_stream_decodes() {
    let out = run("rnc2-old.rnc2");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "RNC");
    assert_eq!(
        out[0].info,
        "RNC2: Rob Northen RNC2 Compressor (old), decoded stream verified, 4 bytes unpacked"
    );
}

/// Locked stream whose literal run is XORed with the low byte of the
/// known ProPack collection key 0x04d2 — the decoder must recover it via
/// the `KNOWN_KEYS` path and pass CRC verification.
#[test]
fn rnc1_encrypted_known_key_decodes() {
    let out = run("rnc1-enc-known.rnc1");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "RNC");
    assert_eq!(
        out[0].info,
        "RNC1: Rob Northen RNC1 Compressor, decoded stream verified, 4 bytes unpacked"
    );
}

/// Locked stream with nine literal runs (run indexes 0..8), constraining
/// all 16 key bits — the decoder must recover key 0xBEEF uniquely via
/// the GF(2) key-recovery path.
#[test]
fn rnc1_encrypted_unique_key_decodes() {
    let out = run("rnc1-enc-unique.rnc1");
    assert_eq!(out.len(), 1, "{out:?}");
    assert_eq!(out[0].record_name, "RNC");
    assert_eq!(
        out[0].info,
        "RNC1: Rob Northen RNC1 Compressor, decoded stream verified, 25 bytes unpacked"
    );
}

/// Locked stream whose key is underdetermined (single literal run, key
/// not in `KNOWN_KEYS`): upstream leaves the output encrypted, the CRC
/// verify fails, and no RNC record is emitted. Truncated old/encrypted
/// streams and CRC corruption must likewise fail closed.
#[test]
fn rnc_encrypted_unrecoverable_and_corrupt_rejected() {
    let out = run("rnc1-enc-badkey.rnc1");
    assert!(!out.iter().any(|r| r.record_name == "RNC"), "{out:?}");

    for name in ["rnc1-old.rnc1", "rnc2-old.rnc2", "rnc1-enc-unique.rnc1"] {
        let good = corpus(name);
        for cut in [12usize, good.len() - 1, good.len() - 2] {
            let d = &good[..cut];
            let out = scan(d, sniff_ft(d), oracle_opts());
            assert!(
                !out.iter().any(|r| r.record_name == "RNC"),
                "{name} cut {cut}: {out:?}"
            );
        }
    }
    // Bad raw CRC on the recoverable encrypted stream.
    let mut bad = corpus("rnc1-enc-known.rnc1");
    bad[12] ^= 0xff;
    let out = scan(&bad, sniff_ft(&bad), oracle_opts());
    assert!(!out.iter().any(|r| r.record_name == "RNC"), "{out:?}");
}

/// Upstream `nEntryPointSection` resolves the EP virtual address against
/// the section memory map in reverse order — overlapping VAs resolve to
/// the LAST section (Phase 26 fix; previously file-offset extents were
/// used, which resolves to the first section).
#[test]
fn ep_section_index_uses_va_space() {
    let d = corpus("fsg-v100-two.unpacked.exe");
    let info = diec_nfd::pe::collect(&d).expect("pe collect");
    // Both sections start at VA 0x1000; EP RVA 0x1000 resolves to sec 1.
    assert_eq!(info.entrypoint_section_index(), 1);
}

/// Section names keep their raw case (upstream `SECTION_RECORD.sName`)
/// so section-name scan records match case-sensitively: `.enigma1` →
/// Enigma Virtual Box, `.bxpck` → BoxedApp Packer (Phase 28 fix;
/// previously the parser uppercased names and the CRC scan missed).
#[test]
fn section_name_detects_are_case_sensitive() {
    let out = run("enigmavb-minimal.exe");
    assert!(has(&out, "Protector", "Enigma Virtual Box"), "{out:?}");
    let out = run("boxedapp-minimal.exe");
    assert!(has(&out, "Protector", "BoxedApp Packer"), "{out:?}");

    // Raw-case names are preserved for downstream compares.
    let d = corpus("enigmavb-minimal.exe");
    let info = diec_nfd::pe::collect(&d).expect("pe collect");
    assert!(info.section_names.iter().any(|n| n == ".enigma1"));
    assert!(!info.section_names.iter().any(|n| n == ".ENIGMA1"));
}

/// Phase 46 — `handle_Microsoftoffice`: a `docProps/app.xml` member
/// (0 < unc_size <= 0x4000) emits the Office flavor format record from
/// `<Application>`; `<AppVersion>` carries the version. Oracle-verified
/// over synthetic zips (tools/gen_p46_corpus.py).
#[test]
fn zip_app_xml_emits_office_format_records() {
    // Microsoft Office Word -> WORD record with AppVersion.
    let out = run("office-docx.zip");
    assert!(
        out.iter().any(|r| r.record_type == "Format"
            && r.record_name == "Microsoft Office Word"
            && r.version == "16.0000"),
        "{out:?}"
    );
    // Microsoft Excel -> EXCEL record.
    let out = run("office-xlsx.zip");
    assert!(
        out.iter().any(|r| r.record_type == "Format"
            && r.record_name == "Microsoft Excel"
            && r.version == "12.0"),
        "{out:?}"
    );
    // SheetJS -> EXCEL record with sInfo "SheetJS" (empty version).
    let out = run("office-sheetjs.zip");
    assert!(
        out.iter().any(|r| r.record_type == "Format"
            && r.record_name == "Microsoft Excel"
            && r.version.is_empty()
            && r.info == "SheetJS"),
        "{out:?}"
    );
    // Unknown Application -> bare MICROSOFTOFFICE with AppVersion.
    let out = run("office-plain.zip");
    assert!(
        out.iter().any(|r| r.record_type == "Format"
            && r.record_name == "Microsoft Office"
            && r.version == "9.9"),
        "{out:?}"
    );
    // Missing <Application> still emits MICROSOFTOFFICE + AppVersion.
    let out = run("office-noapp.zip");
    assert!(
        out.iter().any(|r| r.record_type == "Format"
            && r.record_name == "Microsoft Office"
            && r.version == "7.7"),
        "{out:?}"
    );
    // Stored (method 0) members decompress the same.
    let out = run("office-stored.zip");
    assert!(
        out.iter()
            .any(|r| r.record_type == "Format" && r.record_name == "Microsoft Office Word"),
        "{out:?}"
    );
}

/// Phase 46 — upstream size gate: `nUncompressedSize` must be >0 and
/// <=0x4000; outside the gate no Office record is emitted.
#[test]
fn zip_app_xml_size_gate_fail_closed() {
    for name in ["office-big.zip", "office-empty.zip"] {
        let out = run(name);
        assert!(
            !out.iter().any(|r| r.record_name.contains("Office")),
            "{name}: {out:?}"
        );
        assert!(has(&out, "Format", "ZIP"), "{name}: {out:?}");
    }
}

/// Phase 46 — `handle_OpenOffice`: `meta.xml` containing
/// `:opendocument:` emits the OpenDocument format record.
#[test]
fn zip_meta_xml_emits_opendocument() {
    let out = run("odt.zip");
    assert!(
        out.iter()
            .any(|r| r.record_type == "Format" && r.record_name == "Open Document"),
        "{out:?}"
    );
    let out = run("odt-plain.zip");
    assert!(
        !out.iter().any(|r| r.record_name == "Open Document"),
        "{out:?}"
    );
    assert!(has(&out, "Format", "ZIP"), "{out:?}");
}
